// Base de nomes de artistas/bandas conhecidos (versionada no código).
// Gerada a partir das listas TXT enviadas pelo usuário. Serve de base para o
// reforço de classificação; a tabela known_artists (Supabase) adiciona nomes.
export const KNOWN_ARTISTS_SEED: string[] = [
  "100ecss",
  "10cc",
  "13th Floor Elevators",
  "14 Bis",
  "1Kilo",
  "5 Seconds of Summer",
  "50 Cent",
  "509-E",
  "999",
  "A Cor do Som",
  "A Tribe Called Quest",
  "A-ha",
  "ABBA",
  "ABC",
  "Abolição",
  "AC/DC",
  "Adam Ant",
  "Adão Negro",
  "Adele",
  "Adoniran Barbosa",
  "Adriana Calcanhotto",
  "Adriano Celentano",
  "Aerosmith",
  "Agitation Free",
  "Agnaldo Rayol",
  "Agnaldo Timóteo",
  "Agostinho dos Santos",
  "Air",
  "Airto Moreira",
  "Al Di Meola",
  "Al Green",
  "Al Kooper",
  "Alaíde Costa",
  "Alanis Morissette",
  "Albert Ayler",
  "Albert Collins",
  "Albert King",
  "Alceu Valença",
  "Alcione",
  "Alexisonfire",
  "Alfa Mist",
  "Alice Cooper",
  "Alice in Chains",
  "Alien Sex Fiend",
  "Alison Moyet",
  "All That Remains",
  "Almir Guineto",
  "Almir Sater",
  "Alphaville",
  "Amado Batista",
  "Amelinha",
  "Amii Stewart",
  "Amon Düül II",
  "Amorphis",
  "Amy Winehouse",
  "Ana Cañas",
  "Ana Carolina",
  "Ana Frango Elétrico",
  "Anastácia",
  "Anathema",
  "And Also the Trees",
  "Andrew Hill",
  "Angel",
  "Angel Olsen",
  "Angel Witch",
  "Angela Maria",
  "Angela Ro Ro",
  "Angra",
  "Animal as Leaders",
  "Anita Ward",
  "Anitta",
  "Anthrax",
  "Apanhador Só",
  "Aphex Twin",
  "Ara Ketu",
  "Arcade Fire",
  "Arch Enemy",
  "Archers of Loaf",
  "Archie Shepp",
  "Architects",
  "Arctic Monkeys",
  "Aretha Franklin",
  "Ariana Grande",
  "Arlindo Cruz",
  "Armandinho",
  "Arrigo Barnabé",
  "Art",
  "Art Blakey",
  "Art of Noise",
  "Art Popular",
  "Arthur Conley",
  "Arthur Moreira Lima",
  "Arthur Verocai",
  "Ary Lobo",
  "As I Lay Dying",
  "As Mercenárias",
  "ASAP Rocky",
  "Ash Ra Tempel",
  "At the Gates",
  "Atlantis",
  "Atomic Rooster",
  "Atreyu",
  "Audioslave",
  "August Burns Red",
  "Autopsy",
  "Avantasia",
  "Avenged Sevenfold",
  "Avril Lavigne",
  "Azymuth",
  "Babes in Toyland",
  "Bacamarte",
  "Back Door",
  "Baco Exu do Blues",
  "Bad Company",
  "Bad Religion",
  "BadBadNotGood",
  "Baden Powell",
  "BaianaSystem",
  "Bala Desejo",
  "Banda Beijo",
  "Banda Black Rio",
  "Banda Companhia do Pagode",
  "Banda de Pífanos de Caruaru",
  "Banda DeIra",
  "Banda Eva",
  "Banda Mantiqueira",
  "Banda Mel",
  "Banda Metal Ruy",
  "Banda Terra Samba",
  "Bang",
  "Barão Vermelho",
  "Baritalia",
  "Barry White",
  "Bartô Galeno",
  "Bauhaus",
  "Bay City Rollers",
  "BB King",
  "Beach House",
  "Beastie Boys",
  "Bee Gees",
  "Behemoth",
  "Belchior",
  "Belly",
  "Ben E. King",
  "Beti Carvalho",
  "Beto Guedes",
  "Beyoncé",
  "Bezerra da Silva",
  "Big Brother and the Holding Company",
  "Big Daddy Kane",
  "Big Mama Thornton",
  "Bill Evans",
  "Bill Withers",
  "Billie Eilish",
  "Billie Holiday",
  "Billy Idol",
  "Biquini Cavadão",
  "Birth Control",
  "Björk",
  "BK'",
  "Black Alien",
  "Black Country, New Road",
  "Black Flag",
  "Black Midi",
  "Black Sabbath",
  "Black Star",
  "Black Widow",
  "Blind Guardian",
  "Blink-182",
  "Blitz",
  "Bloc Party",
  "Blood, Sweat & Tears",
  "Blue Cheer",
  "Blue Öyster Cult",
  "Bo Diddley",
  "Boards of Canada",
  "Bob Dylan",
  "Bob James",
  "Bobby Womack",
  "Boca Livre",
  "Bola Sete",
  "Bon Iver",
  "Bon Jovi",
  "Bone Thugs-n-Harmony",
  "Boogarins",
  "Booker Little",
  "Bossa Jazz Trio",
  "Bossa Três",
  "Boston",
  "Boy Pablo",
  "Brand X",
  "Breeders",
  "Brigitte Bardot",
  "Bring Me the Horizon",
  "Britney Spears",
  "Bruce Dickinson",
  "Bruce Springsteen",
  "Bruno & Marrone",
  "Bruno Mars",
  "Bryan Adams",
  "BS&T",
  "Buckethead",
  "Buddy Guy",
  "Buddy Holly",
  "Budgie",
  "Buffalo Springfield",
  "Buffalo Tom",
  "Buffy Sainte-Marie",
  "Built to Spill",
  "Bullet for My Valentine",
  "Burzum",
  "Buzzcocks",
  "Cachorro Grande",
  "Cactus",
  "Caetano Veloso",
  "Camaro do Acordeon",
  "Camel",
  "Camisa de Vênus",
  "Camouflage",
  "Can",
  "Candeia",
  "Candy Staton",
  "Cannibal Corpse",
  "Cannonball Adderley",
  "Capital Inicial",
  "Captain Beefheart",
  "Captain Beyond",
  "Caravan",
  "Carl Perkins",
  "Carlos Galhardo",
  "Carlos Lyra",
  "Carly Simon",
  "Carne Doce",
  "Carole King",
  "Carpenter Brut",
  "Cartola",
  "Casa das Máquinas",
  "Cascabulho",
  "Cássia Eller",
  "Cassiano",
  "Cauby Peixoto",
  "Cazuza",
  "Cecil Taylor",
  "Celine Dion",
  "Central Cee",
  "Centúria",
  "Cesar Camargo Mariano",
  "Céu",
  "Chakal",
  "Chappell Roan",
  "Charles Aznavour",
  "Charles Mingus",
  "Charlie Brown Jr.",
  "Charlie Musselwhite",
  "Cheap Trick",
  "Cheiro de Amor",
  "Cher",
  "Chet Atkins",
  "Chet Baker",
  "Chic",
  "Chicago",
  "Chick Corea",
  "Chico Buarque",
  "Chico César",
  "Childish Gambino",
  "Chimarruts",
  "Chiquinho do Acordeon",
  "Chitãozinho",
  "Chitãozinho & Xororó",
  "Chris Brown",
  "Christina Aguilera",
  "Christone 'Kingfish' Ingram",
  "Chuck Berry",
  "Cícero",
  "Cidade Negra",
  "Cilla Black",
  "Circa Survive",
  "Clairo",
  "Clan of Xymox",
  "Clara Nunes",
  "Claudette Soares",
  "Claudia Leitte",
  "Claudio Roditi",
  "Claudya",
  "Claustrofobia",
  "Clifford Brown",
  "Cluster",
  "Cocteau Twins",
  "Coldplay",
  "Cólera",
  "Colosseum",
  "Common",
  "Companhia Paulista de Disco",
  "Comsat Angels",
  "Comunidade Nin-Jitsu",
  "ConeCrewDiretoria",
  "Conjunto 3D",
  "Cordel do Fogo Encantado",
  "Corinne Bailey Rae",
  "Costa Gold",
  "Count Five",
  "Country Joe and the Fish",
  "CPM 22",
  "Cradle of Filth",
  "Craft Spells",
  "Cream",
  "Creedence Clearwater Revival",
  "Criolo",
  "Crosby, Stills, Nash & Young",
  "Cuco",
  "Culture Club",
  "Curtis Mayfield",
  "Curved Air",
  "Cyndi Lauper",
  "Cypress Hill",
  "Daft Punk",
  "Dalva de Oliveira",
  "Daniel",
  "Daniel Caesar",
  "Daniela Mercury",
  "Danilo Caymmi",
  "Danny Gatton",
  "Dark Angel",
  "Dark Tranquillity",
  "Darkthrone",
  "Dave Brubeck",
  "Dave Mason",
  "David Bowie",
  "David Sanborn",
  "De La Soul",
  "Dead Boys",
  "Dead Fish",
  "Dead Kennedys",
  "Dead or Alive",
  "Dean Martin",
  "Death",
  "Death Angel",
  "Death Cab for Cutie",
  "Death From Above 1979",
  "Deep Purple",
  "Def Leppard",
  "Defalla",
  "Deftones",
  "Deicide",
  "Del Shannon",
  "Demon",
  "Demônios da Garoa",
  "Deny e Dino",
  "Denzel Curry",
  "Depeche Mode",
  "Derek and the Dominos",
  "Derek Trucks",
  "Detonautas",
  "Devotos",
  "Devotos de Nossa Senhora Aparecida",
  "Dexter Gordon",
  "Diamond Head",
  "Diana Krall",
  "Diana Ross",
  "Dick Farney",
  "Dicró",
  "Digable Planets",
  "Diiv",
  "Dilsinho",
  "Dimmu Borgir",
  "Dinosaur Jr.",
  "Dio",
  "Dismember",
  "Djavan",
  "Djonga",
  "Doc Watson",
  "Dolly Parton",
  "Dom Salvador",
  "Dom Um Romão",
  "Domi and JD Beck",
  "Dominguinhos",
  "Dona Ivone Lara",
  "Donald Byrd",
  "Donny Hathaway",
  "Dori Caymmi",
  "Doris Monteiro",
  "Dorsal Atlântica",
  "Dr. Dre",
  "Dr. Sin",
  "Drake",
  "Dream Theater",
  "Drive-By Truckers",
  "Dry Cleaning",
  "Dua Lipa",
  "Duda Beat",
  "Duffy",
  "Duquesa",
  "Dust",
  "Dusty Springfield",
  "Eagles",
  "Earl Hooker",
  "Earl Sweatshirt",
  "Earth, Wind & Fire",
  "Eartheater",
  "EarthGang",
  "Ebony",
  "Echo & the Bunnymen",
  "Ed Motta",
  "Eddie Cochran",
  "Edguy",
  "Edison Machado",
  "Édith Piaf",
  "Editors",
  "Ednardo",
  "Edu Lobo",
  "Eduardo Araújo",
  "Egberto Gismonti",
  "Egg",
  "Egotrip",
  "Electric Light Orchestra",
  "Electric Six",
  "Eleventh House",
  "Eliana Pittman",
  "Eliete legal",
  "Elis Regina",
  "Ella Fitzgerald",
  "Elliott Smith",
  "Elmore James",
  "Elomar",
  "Eloy",
  "Elton John",
  "Elvin Bishop",
  "Elvin Jones",
  "Elvis Presley",
  "Elza Soares",
  "Emerson, Lake & Palmer",
  "Emicida",
  "Emilinha Borba",
  "Eminem",
  "Emmylou Harris",
  "Emperor",
  "Empire of the Sun",
  "Engenheiros do Hawaii",
  "English Teacher",
  "Enslaved",
  "Entombed",
  "Enya",
  "Erasmo Carlos",
  "Erasure",
  "Eric B. & Rakim",
  "Eric Clapton",
  "Eric Dolphy",
  "Eric Johnson",
  "Eros Ramazzotti",
  "Estelle",
  "Esther Phillips",
  "Etta James",
  "Eumir Deodato",
  "Evaldo Braga",
  "Evolução",
  "Exaltasamba",
  "Exodus",
  "Ezra Collective",
  "Fabrizio De André",
  "Facção Central",
  "Fafá de Belém",
  "Fagner",
  "Fairport Convention",
  "Faithless",
  "Fall Out Boy",
  "Family",
  "Father John Misty",
  "Fatima Guedes",
  "Faust",
  "Fernanda Abreu",
  "Fernando Mendes",
  "Ferrugem",
  "Fields of the Nephilim",
  "Filipe Ret",
  "Finis Africae",
  "Fiona Apple",
  "Fist",
  "FKA Twigs",
  "Flávio Venturini",
  "Fleet Foxes",
  "Fleetwood Mac",
  "Flo",
  "Floating Points",
  "Flora Purim",
  "Florence Welch",
  "Flotsam and Jetsam",
  "FM-84",
  "Foals",
  "Fogo Cruzado",
  "Fontaines D.C.",
  "Foo Fighters",
  "Forbidden",
  "Foreigner",
  "Forfun",
  "Foster the People",
  "Fotheringay",
  "France Gall",
  "Francis Hime",
  "Francisco Alves",
  "Francisco el Hombre",
  "Françoise Hardy",
  "Frank Ocean",
  "Frank Sinatra",
  "Frank Zappa",
  "Franz Ferdinand",
  "Fred again..",
  "Freddie Hubbard",
  "Freddie Jackson",
  "Freddie King",
  "Freddie Mercury",
  "Freddie Roach",
  "Free",
  "Frejat",
  "Fresno",
  "Froid",
  "Front 242",
  "Frumpy",
  "Fugazi",
  "Fugees",
  "Fundo de Quintal",
  "Funkadelic",
  "Future",
  "Gabor Szabo",
  "Gal Costa",
  "Gamma Ray",
  "Gang 90 e Absurdettes",
  "Gang 90 e das Absurdettes",
  "Gang of Four",
  "Gang Starr",
  "Garotos Podres",
  "Gary Moore",
  "Gary Numan",
  "Geese",
  "Gene Vincent",
  "Generation X",
  "Genesis",
  "Gentle Giant",
  "Geordie",
  "George Benson",
  "George Harrison",
  "George Jones",
  "Georges Brassens",
  "Gera Samba",
  "Geraldo Azevedo",
  "Geraldo Filme",
  "Geraldo Vandré",
  "Gerson Filho",
  "Gerson King Combo",
  "Gianna Nannini",
  "Gilbert Bécaud",
  "Gilberto Gil",
  "Gilgamesh",
  "Gilliard",
  "Girls Aloud",
  "Girlschool",
  "Giveon",
  "Glass Animals",
  "Glen Campbell",
  "Gloria Groove",
  "Gojira",
  "Gong",
  "Gorgoroth",
  "Gorillaz",
  "Gotthard",
  "Grachan Moncur III",
  "Gracie Abrams",
  "Graffiti",
  "Graforreia Xilarmônica",
  "Gram Parsons",
  "Grand Funk Railroad",
  "Grant Green",
  "Grapefruit",
  "Green Day",
  "Grim Reaper",
  "Gritando HC",
  "Grizzly Bear",
  "Grobschnitt",
  "Grover Washington Jr.",
  "Grupo Fundo de Quintal",
  "Grupo Manifesto",
  "Grupo Raça",
  "Grupo Revelação",
  "Guided by Voices",
  "Guilherme Arantes",
  "Guilherme de Brito",
  "Guns N' Roses",
  "Gunship",
  "Guru Guru",
  "Gusttavo Lima",
  "Guthrie Govan",
  "Guy Clark",
  "Gwen Stefani",
  "H P Lovecraft",
  "Haikaiss",
  "Haircut 100",
  "Hamilton de Holanda",
  "HammerFall",
  "Hank Mobley",
  "Hank Williams",
  "Hanói Hanói",
  "Harmonia",
  "Harppia",
  "Hatfield and the North",
  "Hawkwind",
  "Hawthorne Heights",
  "Headhunters",
  "Heaven 17",
  "Helio Delmiro",
  "Helloween",
  "Henrique & Juliano",
  "Heraldo do Monte",
  "Herbie Hancock",
  "Hermeto Pascoal",
  "Herva Doce",
  "Hieroglyphics",
  "High Tide",
  "Hojerizah",
  "Holocausto",
  "Homeshake",
  "Hooverphonic",
  "Horace Silver",
  "Howard Jones",
  "Howlin' Wolf",
  "Humberto Teixeira",
  "Husker Du",
  "Hyldon",
  "Ice Cube",
  "Ice Spice",
  "IDLES",
  "Iggy Pop",
  "Imagine Dragons",
  "Immortal",
  "In Flames",
  "Inimigos do Rei",
  "Inocentes",
  "Interpol",
  "Ira!",
  "Irma Thomas",
  "Iron & Wine",
  "Iron Butterfly",
  "Iron Maiden",
  "Isaac Hayes",
  "Isaiah Rashad",
  "Isotope",
  "Israel & Rodolffo",
  "It's a Beautiful Day",
  "Itamar Assumpção",
  "Ivete Sangalo",
  "Ivone Lara",
  "Iza",
  "J. Cole",
  "J.B. Hutto",
  "J.T. Meirelles",
  "Jackie McLean",
  "Jackson do Pandeiro",
  "Jacopo Pastorius",
  "Jacques Brel",
  "Jade Warrior",
  "Jadsa",
  "Jaguar",
  "Jair Rodrigues",
  "Jane",
  "Jane Birkin",
  "Jane Duboc",
  "Janet Jackson",
  "Janis Ian",
  "Jão",
  "Japan",
  "Jards Macalé",
  "Jay-Z",
  "Jeff Beck",
  "Jeff Buckley",
  "Jefferson Airplane",
  "Jennifer Lopez",
  "Jerry Adriani",
  "Jerry Lee Lewis",
  "Jerusalem",
  "Jethro Tull",
  "JID",
  "Jim Hall",
  "Jimi Hendrix",
  "Jimmy Eat World",
  "Jimmy Reed",
  "Jimmy Smith",
  "Joan Baez",
  "João do Vale",
  "João Gilberto",
  "João Mineiro",
  "Joe Bonamassa",
  "Joe Henderson",
  "Joe Pass",
  "Joe Satriani",
  "Joe Tex",
  "Joe Walsh",
  "Joey Bada$$",
  "John Coltrane",
  "John Frusciante",
  "John Lee Hooker",
  "John Lennon",
  "John Prine",
  "John Scofield",
  "Johnny Cash",
  "Johnny Thunders & The Heartbreakers",
  "Joni Mitchell",
  "Jorge & Mateus",
  "Jorge Aragão",
  "Jorge Ben Jor",
  "Jorge Mautner",
  "Joss Stone",
  "Josyara",
  "Jota Quest",
  "Journey",
  "Jovelina Pérola Negra",
  "Jovem Dionisio",
  "Joy Division",
  "Joyce Moreno",
  "Juarez Moreira",
  "Judas Priest",
  "Judy Collins",
  "Julien Baker",
  "July",
  "Junior Wells",
  "Jup do Bairro",
  "Justice",
  "Justin Timberlake",
  "Kaê Guajajara",
  "Kajagoogoo",
  "Kamasi Washington",
  "Kanye West",
  "Kasabian",
  "Katatonia",
  "Kate Bush",
  "Katinguelê",
  "Katy Perry",
  "kd lang",
  "Keane",
  "Keb' Mo'",
  "Keith Jarrett",
  "Kelly Clarkson",
  "Kendrick Lamar",
  "Kenny Burrell",
  "Kenny Rogers",
  "Khalid",
  "Kid Abelha",
  "Kid Cudi",
  "Kiko Dinucci",
  "Kiko Zambianchi",
  "Killswitch Engage",
  "Kiloucura",
  "King Crimson",
  "King Diamond",
  "Kings of Leon",
  "Kiss",
  "Klaus Schulze",
  "KMFDM",
  "Knower",
  "Koko Taylor",
  "Kool & The Gang",
  "Korn",
  "Korzus",
  "Kraftwerk",
  "Kris Kristofferson",
  "Krisiun",
  "Krokus",
  "KRS-One",
  "L7",
  "L7NNON",
  "Lady Gaga",
  "Laércio de Freitas",
  "Lamb",
  "Lamb of God",
  "Lana Del Rey",
  "Lanny Gordin",
  "Larry Young",
  "Laura Nyro",
  "Laura Pausini",
  "Laurindo Almeida",
  "LaVern Baker",
  "Leci Brandão",
  "Led Zeppelin",
  "Lee Morgan",
  "Leftfield",
  "Legião Urbana",
  "Lenine",
  "Leno e Lilian",
  "Leny Andrade",
  "Leo Ferré",
  "Leo Jaime",
  "Leonard Cohen",
  "Leonardo",
  "Letrux",
  "Lifetime",
  "Lightnin' Hopkins",
  "Lil Wayne",
  "Limp Bizkit",
  "Lindisfarne",
  "Lindomar Castilho",
  "Liniker",
  "Linkin Park",
  "Little Feat",
  "Little Richard",
  "LL Cool J",
  "Lô Borges",
  "Lobão",
  "Lorde",
  "Loretta Lynn",
  "Los Hermanos",
  "Lou Reed",
  "Louis Armstrong",
  "Luan Santana",
  "Lucero",
  "Luciano",
  "Lucifer's Friend",
  "Lucinda Williams",
  "Lucinha Lins",
  "Lúcio Alves",
  "Lucio Battisti",
  "Lucy Dacus",
  "Ludacris",
  "Ludmilla",
  "Luedji Luna",
  "Luísa Sonza",
  "Luiz Carlos da Vila",
  "Luiz Eça",
  "Luiz Gonzaga",
  "Luiz Melodia",
  "Lulu",
  "Lulu Santos",
  "Lupe Fiasco",
  "Luther Allison",
  "Luther Vandross",
  "Lyle Lovett",
  "Lynyrd Skynyrd",
  "Mac DeMarco",
  "Mac Miller",
  "Made in Brazil",
  "Madonna",
  "Magazine",
  "Magdalena Bay",
  "Magic Sam",
  "Maglore",
  "Mahavishnu Orchestra",
  "Maiara",
  "Maiara & Maraisa",
  "Mallu Magalhães",
  "Mance Lipscomb",
  "Maneva",
  "Mano Brown",
  "Maraisa",
  "Marcelo D2",
  "Marcelo Jeneci",
  "Márcia",
  "Marciano",
  "Márcio Greyck",
  "Márcio Montarroyos",
  "Marcos Valle",
  "Marcus Miller",
  "Margareth Menezes",
  "Maria Bethânia",
  "Maria Gadú",
  "Mariah Carey",
  "Mariana Aydar",
  "Marianne Faithfull",
  "Marília Mendonça",
  "Marillion",
  "Marilyn Manson",
  "Marina Lima",
  "Marinês",
  "Mário Zan",
  "Marisa Monte",
  "Mark Knopfler",
  "Marlene",
  "Maroon 5",
  "Martinho da Vila",
  "Marvin Gaye",
  "Márvio Ciribelli",
  "Maskavo",
  "Massive Attack",
  "Mastodon",
  "Matching Mole",
  "Mateus Faz Leno",
  "Matheus & Kauan",
  "Matuê",
  "Mauro Diniz",
  "Max Roach",
  "Maxïmo Park",
  "May Blitz",
  "Mayhem",
  "Mayitz",
  "MC5",
  "Meat Beat Manifesto",
  "Megadeth",
  "Meirelles e Os Copa 5",
  "Melanie",
  "Melly",
  "Melvins",
  "Mercyful Fate",
  "Merle Haggard",
  "Meshuggah",
  "Messias Holanda",
  "Metá Metá",
  "Metallica",
  "Metalmorphose",
  "Metrô",
  "MGMT",
  "Michael Jackson",
  "Michel Polnareff",
  "Michel Teló",
  "Miguel",
  "Mike Bloomfield",
  "Miles Davis",
  "Milionário e José Rico",
  "Miltinho",
  "Milton Banana",
  "Milton Nascimento",
  "Mina",
  "Ministry",
  "Minor Threat",
  "Minutemen",
  "Mississippi Fred McDowell",
  "Mississippi John Hurt",
  "Mitski",
  "Moacyr Franco",
  "Mobb Deep",
  "Moby Grape",
  "Modest Mouse",
  "Modulo 1000",
  "Molejo",
  "Mombojó",
  "Monarco",
  "Moonspell",
  "Morbid Angel",
  "Morengueira",
  "Morrissey",
  "Mos Def",
  "Moska",
  "Moto Perpétuo",
  "Motörhead",
  "Mott the Hoople",
  "Mountain",
  "Móveis Coloniais de Acaju",
  "MPB4",
  "Mud",
  "Muddy Waters",
  "Mudhoney",
  "Mumuzinho",
  "Mundo Livre S/A",
  "Muse",
  "Mutilator",
  "MV Bill",
  "My Chemical Romance",
  "My Dying Bride",
  "N.W.A",
  "Nação Zumbi",
  "Naipe",
  "Nala Sinephro",
  "Nana Caymmi",
  "Naná Vasconcelos",
  "Nara Leão",
  "Nas",
  "Nat King Cole",
  "Natasha Bedingfield",
  "National Health",
  "Natiruts",
  "Ne-Yo",
  "Negritude Junior",
  "Neil Young",
  "Nelly Furtado",
  "Nelson Cavaquinho",
  "Nelson Gonçalves",
  "Nelson Ned",
  "Nenhum de Nós",
  "Neu!",
  "Neutral Milk Hotel",
  "New Order",
  "New York Dolls",
  "Ney Matogrosso",
  "Nick Cave",
  "Nick Drake",
  "Nico",
  "Nightwish",
  "Nik Kershaw",
  "Nina Simone",
  "Nine Inch Nails",
  "Nirvana",
  "Nivaldo Ornelas",
  "NOFX",
  "Noname",
  "Norah Jones",
  "Notorious B.I.G.",
  "Novalis",
  "Novos Baianos",
  "Nuclear Assault",
  "Nucleus",
  "Nx Zero",
  "O Rappa",
  "O Terço",
  "O Terno",
  "Obituary",
  "Odair José",
  "Old 97's",
  "Olho Seco",
  "Olive",
  "Oliver Nelson",
  "Olivia Dean",
  "Olivia Rodrigo",
  "Olodum",
  "OneRepublic",
  "Opeth",
  "Orbital",
  "Orchestral Manoeuvres in the Dark",
  "Oriente",
  "Orlando Silva",
  "Ornette Coleman",
  "Orquestra Imperial",
  "Os 3 do Nordeste",
  "Os Caçulas",
  "Os Cariocas",
  "Os Cascavelletes",
  "Os Diagonais",
  "Os Golden Boys",
  "Os Incríveis",
  "Os Ipanemas",
  "Os Mutantes",
  "Os Renato e Seus Blue Caps",
  "Os Tincoãs",
  "Os Travessos",
  "Os Vips",
  "Osmar Milito",
  "Oswaldinho do Acordeon",
  "Otis Redding",
  "Otis Rush",
  "Outkast",
  "Overdose",
  "Overkill",
  "Ozzy Osbourne",
  "Pabllo Vittar",
  "Panic! At The Disco",
  "Pantera",
  "Paolo Conte",
  "Paradise Lost",
  "Paralamas do Sucesso",
  "Paramore",
  "Pardinho",
  "Parkway Drive",
  "Parliament",
  "Passacoita",
  "Passport",
  "Pat Metheny",
  "Pato Fu",
  "Patrulha do Espaço",
  "Paul Butterfield",
  "Paul Gilbert",
  "Paul McCartney",
  "Paul Young",
  "Paula Fernandes",
  "Paulinho da Viola",
  "Paulo Bellinati",
  "Paulo Moura",
  "Paulo Sérgio",
  "Pavement",
  "Pavilhão 9",
  "Peabo Bryson",
  "Pearl Jam",
  "Pena Branca",
  "Pentangle",
  "Percy Sledge",
  "Péricles",
  "Perigeo",
  "Periphery",
  "Perturbator",
  "Pery Ribeiro",
  "Peso",
  "Pet Shop Boys",
  "Pete Rock & CL Smooth",
  "Peter Gabriel",
  "Petula Clark",
  "Pharoah Sanders",
  "Phil Collins",
  "Phoebe Bridgers",
  "Phoenix",
  "Picassos Falsos",
  "Pineapple StormTV",
  "Pink",
  "Pink Floyd",
  "PinkPantheress",
  "Pino Daniele",
  "Pinto do Acordeão",
  "Pitty",
  "Pixies",
  "Pixote",
  "PJ Harvey",
  "Planet Hemp",
  "Planta e Raiz",
  "Plebe Rude",
  "Ponto de Equilíbrio",
  "Popol Vuh",
  "Porcupine Tree",
  "Portishead",
  "Possessed",
  "Post Malone",
  "Praying Mantis",
  "Prefab Sprout",
  "Preta Gil",
  "Pretty Maids",
  "Prince",
  "Principal Edwards Magic Theatre",
  "Propaganda",
  "Public Enemy",
  "Public Image Ltd",
  "Pusha T",
  "Quarteto em Cy",
  "Queen",
  "Quicksilver Messenger Service",
  "Quinteto Violado",
  "R.E.M.",
  "Raça Negra",
  "Rachel Reis",
  "Racionais MC's",
  "Radio Birdman",
  "Rádio Táxi",
  "Radiohead",
  "Rage Against the Machine",
  "Raimundos",
  "Rainbow",
  "Rakim",
  "Rammstein",
  "Rancid",
  "Raphael Rabello",
  "Rashid",
  "Ratos de Porão",
  "Raul Seixas",
  "Raven",
  "Ray Charles",
  "Raye",
  "Razorlight",
  "Real Estate",
  "Recordando o Vale das Maçãs",
  "Red Hot Chili Peppers",
  "Reflection Eternal",
  "Reflexu's",
  "Reginaldo Rossi",
  "Reinaldo",
  "Renaissance",
  "Renato Russo",
  "Renato Teixeira",
  "REO Speedwagon",
  "Replicantes",
  "Restos de Nada",
  "Return to Forever",
  "Reverend Gary Davis",
  "Rhapsody of Fire",
  "Richard Hell and the Voidoids",
  "Rick Derringer",
  "Rickie Lee Jones",
  "Ricky Nelson",
  "Rihanna",
  "Rincón Sapiência",
  "Ringo Starr",
  "Rita Lee",
  "Ritchie",
  "Rob Halford",
  "Rob Zombie",
  "Robert Johnson",
  "Robertinho do Acordeon",
  "Roberto Carlos",
  "Roberto Ribeiro",
  "Robin Trower",
  "Rock Goddess",
  "Rod Stewart",
  "Roland Kirk",
  "Rômulo Fróes",
  "Ronnie Montrose",
  "Ronnie Von",
  "Rory Gallagher",
  "Rosinha de Valença",
  "Rotting Christ",
  "Roupa Nova",
  "Roxy Music",
  "Roy Buchanan",
  "Roy Haynes",
  "Roy Orbison",
  "RPM",
  "Run-D.M.C.",
  "Rush",
  "Ruth Brown",
  "RZO",
  "Sá e Guarabyra",
  "Sá, Rodrix & Guarabyra",
  "Saba",
  "Sabotage",
  "Sabrina Carpenter",
  "Sacred Reich",
  "Sad Lovers & Giants",
  "Sade",
  "Sadus",
  "Salário Mínimo",
  "Sam Cooke",
  "Sambalanço Trio",
  "Sampa Crew",
  "Sampha",
  "Samson",
  "Sandi Shaw",
  "Sandra de Sá",
  "Santana",
  "Saosin",
  "Sarah Vaughan",
  "Sarcófago",
  "Satyricon",
  "Saxon",
  "Scalene",
  "Scorpions",
  "Screaming Trees",
  "Scritti Politti",
  "Sebastião Tapajós",
  "Secos & Molhados",
  "Sem Compromisso",
  "Sempre Livre",
  "Sensação",
  "Senses Fail",
  "Septicflesh",
  "Sepultura",
  "Serge Gainsbourg",
  "Serginho Meriti",
  "Sergio Mendes",
  "Sérgio Mendes & Brasil '66",
  "Sergio Reis",
  "Sérgio Sampaio",
  "Seu Jorge",
  "Sex Pistols",
  "Shabaka Hutchings",
  "Shadows Fall",
  "Shakira",
  "Shaman",
  "Shame",
  "Sheryl Crow",
  "Shygirl",
  "Silva",
  "Silverstein",
  "Silvinha Araújo",
  "Silvinho",
  "Simaria",
  "Simon & Garfunkel",
  "Simone Mendes",
  "Simple Minds",
  "Simple Plan",
  "Sinéad O'Connor",
  "Siouxsie and the Banshees",
  "Sir Lord Baltimore",
  "Sister Rosetta Tharpe",
  "Sister Sledge",
  "Sisters of Mercy",
  "Sivuca",
  "Skank",
  "Skinny Puppy",
  "Skip James",
  "Slade",
  "Slash",
  "Slayer",
  "Slayyyter",
  "Slim Harpo",
  "Slipknot",
  "Slobberbone",
  "Slum Village",
  "Sly and the Family Stone",
  "Smashing Pumpkins",
  "Smino",
  "Snarky Puppy",
  "Sneaker Pimps",
  "SNJ",
  "Snoop Dogg",
  "Snow Patrol",
  "Soft Cell",
  "Soft Machine",
  "Soilwork",
  "Solomon Burke",
  "Som Imagina'rio",
  "Som Imaginário",
  "Som Nosso de Cada Dia",
  "Sombrinha",
  "Son Seals",
  "Son Volt",
  "Sonata Arctica",
  "Sonic Youth",
  "Sonny Boy Williamson II",
  "Sonny Rollins",
  "Sons of Kemet",
  "Sophia Chablau e Uma Enorme Perda de Tempo",
  "Sophie Ellis-Bextor",
  "Souls of Mischief",
  "Soundgarden",
  "Soweto",
  "Spandau Ballet",
  "Spanky and Our Gang",
  "SPC (Só Pra Contrariar)",
  "Spirit",
  "SpokFrevo Orquestra",
  "Spooky Tooth",
  "Spoon",
  "Sprints",
  "Squid",
  "St. Vincent",
  "Stan Getz",
  "Starz",
  "Steeleye Span",
  "Steely Dan",
  "Steppenwolf",
  "Steve Earle",
  "Steve Vai",
  "Steve Winwood",
  "Stevie Ray Vaughan",
  "Stevie Wonder",
  "Stiff Little Fingers",
  "Sting",
  "Stone Temple Pilots",
  "Story of the Year",
  "Stratovarius",
  "Strawberry Alarm Clock",
  "Strawbs",
  "Stray",
  "Stress",
  "Strike",
  "Styx",
  "Sued Nunes",
  "Sueli Costa",
  "Sufjan Stevens",
  "Sugababes",
  "Sum 41",
  "Sun Ra",
  "Superchunk",
  "Supercombo",
  "Supertramp",
  "Suricato",
  "Sweet",
  "Sylvinha Telles",
  "System of a Down",
  "T. Rex",
  "Taiguara",
  "Taj Mahal",
  "Taking Back Sunday",
  "Talib Kweli",
  "Talk Talk",
  "Talking Heads",
  "Tamba Trio",
  "Tame Impala",
  "Tammy Wynette",
  "Tangerine Dream",
  "Tânia Maria",
  "Tasha & Tracie",
  "Tate McRae",
  "Taylor Swift",
  "Tears for Fears",
  "Ted Nugent",
  "Teddy Pendergrass",
  "Television",
  "Ten Years After",
  "Tenório Jr.",
  "Terno Rei",
  "Terreno Baldio",
  "Testament",
  "Tetê da Represa",
  "Tetê Espíndola",
  "The 1975",
  "The Action",
  "The Adverts",
  "The Allman Brothers Band",
  "The Animals",
  "The Archies",
  "The Association",
  "The Attack",
  "The Automatic",
  "The Avengers",
  "The Beach Boys",
  "The Beatles",
  "The Birthday Party",
  "The Black Keys",
  "The Blue Nile",
  "The BoDeans",
  "The Bottle Rockets",
  "The Bravery",
  "The Buckinghams",
  "The Byrds",
  "The Call",
  "The Chameleons",
  "The Champs",
  "The Chantays",
  "The Chemical Brothers",
  "The Chocolate Watchband",
  "The Church",
  "The Clash",
  "The Cleavers",
  "The Comet Is Coming",
  "The Commodores",
  "The Cowsills",
  "The Cramps",
  "The Creation",
  "The Cribs",
  "The Cure",
  "The Damned",
  "The Dave Clark Five",
  "The Dictators",
  "The Doobie Brothers",
  "The Doors",
  "The Electric Prunes",
  "The Enemy",
  "The Faces",
  "The Fall",
  "The Fevers",
  "The Fifth Dimension",
  "The Fixx",
  "The Four Tops",
  "The Fratellis",
  "The Futureheads",
  "The Germs",
  "The Go-Betweens",
  "The Grass Roots",
  "The Gun Club",
  "The Hollies",
  "The Hooters",
  "The Housemartins",
  "The Human League",
  "The Idle Race",
  "The Incredible String Band",
  "The Isley Brothers",
  "The Jackson 5",
  "The Jayhawks",
  "The Jet Black's",
  "The Jimi Hendrix Experience",
  "The Killers",
  "The Kinks",
  "The Kooks",
  "The Last Dinner Party",
  "The Lemonheads",
  "The Libertines",
  "The Lovin' Spoonful",
  "The Mamas & the Papas",
  "The Mavericks",
  "The Members",
  "The Midnight",
  "The Mission",
  "The Modern Lovers",
  "The Monkees",
  "The Murder Capital",
  "The Music Machine",
  "The National",
  "The Nice",
  "The O'Jays",
  "The Offspring",
  "The Orb",
  "The Outfield",
  "The Partridge Family",
  "The Pentangle",
  "The Pharcyde",
  "The Pigeon Detectives",
  "The Police",
  "The Postal Service",
  "The Pretty Things",
  "The Prodigy",
  "The Psychedelic Furs",
  "The Ramones",
  "The Replacements",
  "The Rolling Stones",
  "The Roots",
  "The Ruts",
  "The Saints",
  "The Searchers",
  "The Seeds",
  "The Shadows",
  "The Shins",
  "The Small Faces",
  "The Smiths",
  "The Soft Machine",
  "The Sonics",
  "The Sound",
  "The Spencer Davis Group",
  "The Spinners",
  "The Spotnicks",
  "The Standells",
  "The Stooges",
  "The Strokes",
  "The Subways",
  "The Supremes",
  "The Surfaris",
  "The Temptations",
  "The Tornados",
  "The Trammps",
  "The Tremeloes",
  "The Triffids",
  "The Troggs",
  "The Turtles",
  "The Used",
  "The Velvet Underground",
  "The Ventures",
  "The Vibrators",
  "The Wedding Present",
  "The Weeknd",
  "The Weirdos",
  "The White Stripes",
  "The Who",
  "The Yardbirds",
  "The Young Rascals",
  "The Zombies",
  "Thelonious Monk",
  "Thiaguinho",
  "Thin Lizzy",
  "Third Ear Band",
  "Thomas Dolby",
  "Thompson Twins",
  "Throwing Muses",
  "Thursday",
  "Tiago Iorc",
  "Tiamat",
  "Tião Carreiro",
  "Ties de Souza",
  "Tihuana",
  "Tim Bernardes",
  "Tim Buckley",
  "Tim Maia",
  "Timbalada",
  "Tina Turner",
  "Tinoco",
  "Titãs",
  "TNT",
  "Toad",
  "Tokyo Blade",
  "Tom Jobim",
  "Tom Morello",
  "Tom Petty",
  "Tom Waits",
  "Tomorrow",
  "Tonico",
  "Toninho Horta",
  "Tony Bennett",
  "Tool",
  "Toquinho",
  "Tori Amos",
  "Torture Squad",
  "Toto",
  "Tower of Power",
  "Townes Van Zandt",
  "Tracy Chapman",
  "Trapeze",
  "Travis Scott",
  "Trees",
  "Tribo da Periferia",
  "Tribo de Jah",
  "Tricky",
  "Trio Mocotó",
  "Trio Nordestino",
  "Trio Parada Dura",
  "Trio Virgulino",
  "Trivium",
  "Tulipa Ruiz",
  "Tupac Shakur",
  "Turíbio Santos",
  "Turma do Pagode",
  "Tutti Frutti",
  "Tuyo",
  "TV on the Radio",
  "Twenty One Pilots",
  "Two Door Cinema Club",
  "Tygers of Pan Tang",
  "Tyler, the Creator",
  "U2",
  "UFO",
  "Ultraje a Rigor",
  "Ultramen",
  "Ultravox",
  "Uncle Tupelo",
  "Underoath",
  "Underworld",
  "Unearth",
  "União Black",
  "Uriah Heep",
  "Urias",
  "Usher",
  "Vampire Weekend",
  "Van der Graaf Generator",
  "Van Halen",
  "Vanessa da Mata",
  "Vanguart",
  "Vanilla Fudge",
  "Vardis",
  "Veruca Salt",
  "Vicente Celestino",
  "Victor & Leo",
  "Victor Wooten",
  "Vimana",
  "Vince Staples",
  "Vinicius de Moraes",
  "Vio-Lence",
  "Violent Femmes",
  "Viper",
  "Virna Lisi",
  "Visage",
  "Vital Farias",
  "Wagner Tiso",
  "Waldick Soriano",
  "Wallenstein",
  "Walter Franco",
  "Wanda Sá",
  "Wanderléa",
  "Wanderley Cardoso",
  "Warren Haynes",
  "Waylon Jennings",
  "Wayne Shorter",
  "We Are Scientists",
  "Weather Report",
  "Wes Montgomery",
  "Wet Leg",
  "Whiskeytown",
  "Whitesnake",
  "Whitney Houston",
  "Wilco",
  "Wild Nothing",
  "Willie Nelson",
  "Wilson Moreira",
  "Wilson Pickett",
  "Wilson Simonal",
  "Wire",
  "Wishbone Ash",
  "Witchfynde",
  "Wizzard",
  "Wu-Tang Clan",
  "Xamã",
  "Xande de Pilares",
  "Xangai",
  "Xavantinho",
  "Xenia França",
  "Xororó",
  "Yamandu Costa",
  "Yard Act",
  "Yello",
  "Yes",
  "Yngwie Malmsteen",
  "Young Thug",
  "Yusef Lateef",
  "Yussef Kamaal",
  "Yves Montand",
  "Zé Neto & Cristiano",
  "Zé Ramalho",
  "Zeca Baleiro",
  "Zeca Pagodinho",
  "Zélia Duncan",
  "Zero",
  "Zezé Di Camargo",
  "Zimbo Trio",
  "Zucchero",
  "ZZ Top",
];
