/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as VinilAnalyticsPublicoRouteImport } from './routes/vinil-analytics-publico'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedAnaliseRouteImport } from './routes/_authenticated/analise'
import { Route as AuthenticatedAoVivoRouteImport } from './routes/_authenticated/ao-vivo'
import { Route as AuthenticatedColecaoRouteImport } from './routes/_authenticated/colecao'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedVinilAnalyticsRouteImport } from './routes/_authenticated/vinil-analytics'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const VinilAnalyticsPublicoRoute = VinilAnalyticsPublicoRouteImport.update({
  id: '/vinil-analytics-publico',
  path: '/vinil-analytics-publico',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnaliseRoute = AuthenticatedAnaliseRouteImport.update({
  id: '/analise',
  path: '/analise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAoVivoRoute = AuthenticatedAoVivoRouteImport.update({
  id: '/ao-vivo',
  path: '/ao-vivo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColecaoRoute = AuthenticatedColecaoRouteImport.update({
  id: '/colecao',
  path: '/colecao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVinilAnalyticsRoute =
  AuthenticatedVinilAnalyticsRouteImport.update({
    id: '/vinil-analytics',
    path: '/vinil-analytics',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/vinil-analytics-publico': typeof VinilAnalyticsPublicoRoute
  '/analise': typeof AuthenticatedAnaliseRoute
  '/ao-vivo': typeof AuthenticatedAoVivoRoute
  '/colecao': typeof AuthenticatedColecaoRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/vinil-analytics': typeof AuthenticatedVinilAnalyticsRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/vinil-analytics-publico': typeof VinilAnalyticsPublicoRoute
  '/analise': typeof AuthenticatedAnaliseRoute
  '/ao-vivo': typeof AuthenticatedAoVivoRoute
  '/colecao': typeof AuthenticatedColecaoRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/vinil-analytics': typeof AuthenticatedVinilAnalyticsRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/vinil-analytics-publico': typeof VinilAnalyticsPublicoRoute
  '/_authenticated/analise': typeof AuthenticatedAnaliseRoute
  '/_authenticated/ao-vivo': typeof AuthenticatedAoVivoRoute
  '/_authenticated/colecao': typeof AuthenticatedColecaoRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/vinil-analytics': typeof AuthenticatedVinilAnalyticsRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/vinil-analytics-publico'
    | '/analise'
    | '/ao-vivo'
    | '/colecao'
    | '/compras'
    | '/vinil-analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/vinil-analytics-publico'
    | '/analise'
    | '/ao-vivo'
    | '/colecao'
    | '/compras'
    | '/vinil-analytics'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/vinil-analytics-publico'
    | '/_authenticated/analise'
    | '/_authenticated/ao-vivo'
    | '/_authenticated/colecao'
    | '/_authenticated/compras'
    | '/_authenticated/vinil-analytics'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VinilAnalyticsPublicoRoute: typeof VinilAnalyticsPublicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vinil-analytics-publico': {
      id: '/vinil-analytics-publico'
      path: '/vinil-analytics-publico'
      fullPath: '/vinil-analytics-publico'
      preLoaderRoute: typeof VinilAnalyticsPublicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analise': {
      id: '/_authenticated/analise'
      path: '/analise'
      fullPath: '/analise'
      preLoaderRoute: typeof AuthenticatedAnaliseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ao-vivo': {
      id: '/_authenticated/ao-vivo'
      path: '/ao-vivo'
      fullPath: '/ao-vivo'
      preLoaderRoute: typeof AuthenticatedAoVivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colecao': {
      id: '/_authenticated/colecao'
      path: '/colecao'
      fullPath: '/colecao'
      preLoaderRoute: typeof AuthenticatedColecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vinil-analytics': {
      id: '/_authenticated/vinil-analytics'
      path: '/vinil-analytics'
      fullPath: '/vinil-analytics'
      preLoaderRoute: typeof AuthenticatedVinilAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnaliseRoute: typeof AuthenticatedAnaliseRoute
  AuthenticatedAoVivoRoute: typeof AuthenticatedAoVivoRoute
  AuthenticatedColecaoRoute: typeof AuthenticatedColecaoRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedVinilAnalyticsRoute: typeof AuthenticatedVinilAnalyticsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnaliseRoute: AuthenticatedAnaliseRoute,
  AuthenticatedAoVivoRoute: AuthenticatedAoVivoRoute,
  AuthenticatedColecaoRoute: AuthenticatedColecaoRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedVinilAnalyticsRoute: AuthenticatedVinilAnalyticsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VinilAnalyticsPublicoRoute: VinilAnalyticsPublicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
