-- Base de nomes de artistas/bandas conhecidos para reforçar a classificação
-- de lotes que a heurística deixa como "não classificados".
-- Seed gerado a partir das listas TXT enviadas pelo usuário (1649 nomes únicos).

CREATE TABLE IF NOT EXISTS public.known_artists (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  name_norm TEXT NOT NULL UNIQUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT SELECT ON public.known_artists TO authenticated;
GRANT ALL ON public.known_artists TO service_role;
ALTER TABLE public.known_artists ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Authenticated users can view known artists"
  ON public.known_artists FOR SELECT TO authenticated USING (true);

INSERT INTO public.known_artists (name, name_norm) VALUES
  ('100ecss', '100ecss'),
  ('10cc', '10cc'),
  ('13th Floor Elevators', '13th floor elevators'),
  ('14 Bis', '14 bis'),
  ('1Kilo', '1kilo'),
  ('5 Seconds of Summer', '5 seconds of summer'),
  ('50 Cent', '50 cent'),
  ('509-E', '509 e'),
  ('999', '999'),
  ('A Cor do Som', 'a cor do som'),
  ('A-ha', 'a ha'),
  ('A Tribe Called Quest', 'a tribe called quest'),
  ('ABBA', 'abba'),
  ('ABC', 'abc'),
  ('Abolição', 'abolicao'),
  ('AC/DC', 'ac dc'),
  ('Adam Ant', 'adam ant'),
  ('Adão Negro', 'adao negro'),
  ('Adele', 'adele'),
  ('Adoniran Barbosa', 'adoniran barbosa'),
  ('Adriana Calcanhotto', 'adriana calcanhotto'),
  ('Adriano Celentano', 'adriano celentano'),
  ('Aerosmith', 'aerosmith'),
  ('Agitation Free', 'agitation free'),
  ('Agnaldo Rayol', 'agnaldo rayol'),
  ('Agnaldo Timóteo', 'agnaldo timoteo'),
  ('Agostinho dos Santos', 'agostinho dos santos'),
  ('Air', 'air'),
  ('Airto Moreira', 'airto moreira'),
  ('Al Di Meola', 'al di meola'),
  ('Al Green', 'al green'),
  ('Al Kooper', 'al kooper'),
  ('Alaíde Costa', 'alaide costa'),
  ('Alanis Morissette', 'alanis morissette'),
  ('Albert Ayler', 'albert ayler'),
  ('Albert Collins', 'albert collins'),
  ('Albert King', 'albert king'),
  ('Alceu Valença', 'alceu valenca'),
  ('Alcione', 'alcione'),
  ('Alexisonfire', 'alexisonfire'),
  ('Alfa Mist', 'alfa mist'),
  ('Alice Cooper', 'alice cooper'),
  ('Alice in Chains', 'alice in chains'),
  ('Alien Sex Fiend', 'alien sex fiend'),
  ('Alison Moyet', 'alison moyet'),
  ('All That Remains', 'all that remains'),
  ('Almir Guineto', 'almir guineto'),
  ('Almir Sater', 'almir sater'),
  ('Alphaville', 'alphaville'),
  ('Amado Batista', 'amado batista'),
  ('Amelinha', 'amelinha'),
  ('Amii Stewart', 'amii stewart'),
  ('Amon Düül II', 'amon duul ii'),
  ('Amorphis', 'amorphis'),
  ('Amy Winehouse', 'amy winehouse'),
  ('Ana Cañas', 'ana canas'),
  ('Ana Carolina', 'ana carolina'),
  ('Ana Frango Elétrico', 'ana frango eletrico'),
  ('Anastácia', 'anastacia'),
  ('Anathema', 'anathema'),
  ('And Also the Trees', 'and also the trees'),
  ('Andrew Hill', 'andrew hill'),
  ('Angel', 'angel'),
  ('Angel Olsen', 'angel olsen'),
  ('Angel Witch', 'angel witch'),
  ('Angela Maria', 'angela maria'),
  ('Angela Ro Ro', 'angela ro ro'),
  ('Angra', 'angra'),
  ('Animal as Leaders', 'animal as leaders'),
  ('Anita Ward', 'anita ward'),
  ('Anitta', 'anitta'),
  ('Anthrax', 'anthrax'),
  ('Apanhador Só', 'apanhador so'),
  ('Aphex Twin', 'aphex twin'),
  ('Ara Ketu', 'ara ketu'),
  ('Arcade Fire', 'arcade fire'),
  ('Arch Enemy', 'arch enemy'),
  ('Archers of Loaf', 'archers of loaf'),
  ('Archie Shepp', 'archie shepp'),
  ('Architects', 'architects'),
  ('Arctic Monkeys', 'arctic monkeys'),
  ('Aretha Franklin', 'aretha franklin'),
  ('Ariana Grande', 'ariana grande'),
  ('Arlindo Cruz', 'arlindo cruz'),
  ('Armandinho', 'armandinho'),
  ('Arrigo Barnabé', 'arrigo barnabe'),
  ('Art', 'art'),
  ('Art Blakey', 'art blakey'),
  ('Art of Noise', 'art of noise'),
  ('Art Popular', 'art popular'),
  ('Arthur Conley', 'arthur conley'),
  ('Arthur Moreira Lima', 'arthur moreira lima'),
  ('Arthur Verocai', 'arthur verocai'),
  ('Ary Lobo', 'ary lobo'),
  ('As I Lay Dying', 'as i lay dying'),
  ('As Mercenárias', 'as mercenarias'),
  ('ASAP Rocky', 'asap rocky'),
  ('Ash Ra Tempel', 'ash ra tempel'),
  ('At the Gates', 'at the gates'),
  ('Atlantis', 'atlantis'),
  ('Atomic Rooster', 'atomic rooster'),
  ('Atreyu', 'atreyu'),
  ('Audioslave', 'audioslave'),
  ('August Burns Red', 'august burns red'),
  ('Autopsy', 'autopsy'),
  ('Avantasia', 'avantasia'),
  ('Avenged Sevenfold', 'avenged sevenfold'),
  ('Avril Lavigne', 'avril lavigne'),
  ('Azymuth', 'azymuth'),
  ('Babes in Toyland', 'babes in toyland'),
  ('Bacamarte', 'bacamarte'),
  ('Back Door', 'back door'),
  ('Baco Exu do Blues', 'baco exu do blues'),
  ('Bad Company', 'bad company'),
  ('Bad Religion', 'bad religion'),
  ('BadBadNotGood', 'badbadnotgood'),
  ('Baden Powell', 'baden powell'),
  ('BaianaSystem', 'baianasystem'),
  ('Bala Desejo', 'bala desejo'),
  ('Banda Beijo', 'banda beijo'),
  ('Banda Black Rio', 'banda black rio'),
  ('Banda Companhia do Pagode', 'banda companhia do pagode'),
  ('Banda de Pífanos de Caruaru', 'banda de pifanos de caruaru'),
  ('Banda DeIra', 'banda deira'),
  ('Banda Eva', 'banda eva'),
  ('Banda Mantiqueira', 'banda mantiqueira'),
  ('Banda Mel', 'banda mel'),
  ('Banda Metal Ruy', 'banda metal ruy'),
  ('Banda Terra Samba', 'banda terra samba'),
  ('Bang', 'bang'),
  ('Barão Vermelho', 'barao vermelho'),
  ('Baritalia', 'baritalia'),
  ('Barry White', 'barry white'),
  ('Bartô Galeno', 'barto galeno'),
  ('Bauhaus', 'bauhaus'),
  ('Bay City Rollers', 'bay city rollers'),
  ('BB King', 'bb king'),
  ('Beach House', 'beach house'),
  ('Beastie Boys', 'beastie boys'),
  ('Bee Gees', 'bee gees'),
  ('Behemoth', 'behemoth'),
  ('Belchior', 'belchior'),
  ('Belly', 'belly'),
  ('Ben E. King', 'ben e king'),
  ('Beti Carvalho', 'beti carvalho'),
  ('Beto Guedes', 'beto guedes'),
  ('Beyoncé', 'beyonce'),
  ('Bezerra da Silva', 'bezerra da silva'),
  ('Big Brother and the Holding Company', 'big brother and the holding company'),
  ('Big Daddy Kane', 'big daddy kane'),
  ('Big Mama Thornton', 'big mama thornton'),
  ('Bill Evans', 'bill evans'),
  ('Bill Withers', 'bill withers'),
  ('Billie Eilish', 'billie eilish'),
  ('Billie Holiday', 'billie holiday'),
  ('Billy Idol', 'billy idol'),
  ('Biquini Cavadão', 'biquini cavadao'),
  ('Birth Control', 'birth control'),
  ('Björk', 'bjork'),
  ('BK''', 'bk'),
  ('Black Alien', 'black alien'),
  ('Black Country, New Road', 'black country new road'),
  ('Black Flag', 'black flag'),
  ('Black Midi', 'black midi'),
  ('Black Sabbath', 'black sabbath'),
  ('Black Star', 'black star'),
  ('Black Widow', 'black widow'),
  ('Blind Guardian', 'blind guardian'),
  ('Blink-182', 'blink 182'),
  ('Blitz', 'blitz'),
  ('Bloc Party', 'bloc party'),
  ('Blood, Sweat & Tears', 'blood sweat tears'),
  ('Blue Cheer', 'blue cheer'),
  ('Blue Öyster Cult', 'blue oyster cult'),
  ('Bo Diddley', 'bo diddley'),
  ('Boards of Canada', 'boards of canada'),
  ('Bob Dylan', 'bob dylan'),
  ('Bob James', 'bob james'),
  ('Bobby Womack', 'bobby womack'),
  ('Boca Livre', 'boca livre'),
  ('Bola Sete', 'bola sete'),
  ('Bon Iver', 'bon iver'),
  ('Bon Jovi', 'bon jovi'),
  ('Bone Thugs-n-Harmony', 'bone thugs n harmony'),
  ('Boogarins', 'boogarins'),
  ('Booker Little', 'booker little'),
  ('Bossa Jazz Trio', 'bossa jazz trio'),
  ('Bossa Três', 'bossa tres'),
  ('Boston', 'boston'),
  ('Boy Pablo', 'boy pablo'),
  ('Brand X', 'brand x'),
  ('Breeders', 'breeders'),
  ('Brigitte Bardot', 'brigitte bardot'),
  ('Bring Me the Horizon', 'bring me the horizon'),
  ('Britney Spears', 'britney spears'),
  ('Bruce Dickinson', 'bruce dickinson'),
  ('Bruce Springsteen', 'bruce springsteen'),
  ('Bruno & Marrone', 'bruno marrone'),
  ('Bruno Mars', 'bruno mars'),
  ('Bryan Adams', 'bryan adams'),
  ('BS&T', 'bs t'),
  ('Buckethead', 'buckethead'),
  ('Buddy Guy', 'buddy guy'),
  ('Buddy Holly', 'buddy holly'),
  ('Budgie', 'budgie'),
  ('Buffalo Springfield', 'buffalo springfield'),
  ('Buffalo Tom', 'buffalo tom'),
  ('Buffy Sainte-Marie', 'buffy sainte marie'),
  ('Built to Spill', 'built to spill'),
  ('Bullet for My Valentine', 'bullet for my valentine'),
  ('Burzum', 'burzum'),
  ('Buzzcocks', 'buzzcocks'),
  ('Cachorro Grande', 'cachorro grande'),
  ('Cactus', 'cactus'),
  ('Caetano Veloso', 'caetano veloso'),
  ('Camaro do Acordeon', 'camaro do acordeon'),
  ('Camel', 'camel'),
  ('Camisa de Vênus', 'camisa de venus'),
  ('Camouflage', 'camouflage'),
  ('Can', 'can'),
  ('Candeia', 'candeia'),
  ('Candy Staton', 'candy staton'),
  ('Cannibal Corpse', 'cannibal corpse'),
  ('Cannonball Adderley', 'cannonball adderley'),
  ('Capital Inicial', 'capital inicial'),
  ('Captain Beefheart', 'captain beefheart'),
  ('Captain Beyond', 'captain beyond'),
  ('Caravan', 'caravan'),
  ('Carl Perkins', 'carl perkins'),
  ('Carlos Galhardo', 'carlos galhardo'),
  ('Carlos Lyra', 'carlos lyra'),
  ('Carly Simon', 'carly simon'),
  ('Carne Doce', 'carne doce'),
  ('Carole King', 'carole king'),
  ('Carpenter Brut', 'carpenter brut'),
  ('Cartola', 'cartola'),
  ('Casa das Máquinas', 'casa das maquinas'),
  ('Cascabulho', 'cascabulho'),
  ('Cássia Eller', 'cassia eller'),
  ('Cassiano', 'cassiano'),
  ('Cauby Peixoto', 'cauby peixoto'),
  ('Cazuza', 'cazuza'),
  ('Cecil Taylor', 'cecil taylor'),
  ('Celine Dion', 'celine dion'),
  ('Central Cee', 'central cee'),
  ('Centúria', 'centuria'),
  ('Cesar Camargo Mariano', 'cesar camargo mariano'),
  ('Céu', 'ceu'),
  ('Chakal', 'chakal'),
  ('Chappell Roan', 'chappell roan'),
  ('Charles Aznavour', 'charles aznavour'),
  ('Charles Mingus', 'charles mingus'),
  ('Charlie Brown Jr.', 'charlie brown jr'),
  ('Charlie Musselwhite', 'charlie musselwhite'),
  ('Cheap Trick', 'cheap trick'),
  ('Cheiro de Amor', 'cheiro de amor'),
  ('Cher', 'cher'),
  ('Chet Atkins', 'chet atkins'),
  ('Chet Baker', 'chet baker'),
  ('Chic', 'chic'),
  ('Chicago', 'chicago'),
  ('Chick Corea', 'chick corea'),
  ('Chico Buarque', 'chico buarque'),
  ('Chico César', 'chico cesar'),
  ('Childish Gambino', 'childish gambino'),
  ('Chimarruts', 'chimarruts'),
  ('Chiquinho do Acordeon', 'chiquinho do acordeon'),
  ('Chitãozinho', 'chitaozinho'),
  ('Chitãozinho & Xororó', 'chitaozinho xororo'),
  ('Chris Brown', 'chris brown'),
  ('Christina Aguilera', 'christina aguilera'),
  ('Christone ''Kingfish'' Ingram', 'christone kingfish ingram'),
  ('Chuck Berry', 'chuck berry'),
  ('Cícero', 'cicero'),
  ('Cidade Negra', 'cidade negra'),
  ('Cilla Black', 'cilla black'),
  ('Circa Survive', 'circa survive'),
  ('Clairo', 'clairo'),
  ('Clan of Xymox', 'clan of xymox'),
  ('Clara Nunes', 'clara nunes'),
  ('Claudette Soares', 'claudette soares'),
  ('Claudia Leitte', 'claudia leitte'),
  ('Claudio Roditi', 'claudio roditi'),
  ('Claudya', 'claudya'),
  ('Claustrofobia', 'claustrofobia'),
  ('Clifford Brown', 'clifford brown'),
  ('Cluster', 'cluster'),
  ('Cocteau Twins', 'cocteau twins'),
  ('Coldplay', 'coldplay'),
  ('Cólera', 'colera'),
  ('Colosseum', 'colosseum'),
  ('Common', 'common'),
  ('Companhia Paulista de Disco', 'companhia paulista de disco'),
  ('Comsat Angels', 'comsat angels'),
  ('Comunidade Nin-Jitsu', 'comunidade nin jitsu'),
  ('ConeCrewDiretoria', 'conecrewdiretoria'),
  ('Conjunto 3D', 'conjunto 3d'),
  ('Cordel do Fogo Encantado', 'cordel do fogo encantado'),
  ('Corinne Bailey Rae', 'corinne bailey rae'),
  ('Costa Gold', 'costa gold'),
  ('Count Five', 'count five'),
  ('Country Joe and the Fish', 'country joe and the fish'),
  ('CPM 22', 'cpm 22'),
  ('Cradle of Filth', 'cradle of filth'),
  ('Craft Spells', 'craft spells'),
  ('Cream', 'cream'),
  ('Creedence Clearwater Revival', 'creedence clearwater revival'),
  ('Criolo', 'criolo'),
  ('Crosby, Stills, Nash & Young', 'crosby stills nash young'),
  ('Cuco', 'cuco'),
  ('Culture Club', 'culture club'),
  ('Curtis Mayfield', 'curtis mayfield'),
  ('Curved Air', 'curved air'),
  ('Cyndi Lauper', 'cyndi lauper'),
  ('Cypress Hill', 'cypress hill'),
  ('Daft Punk', 'daft punk'),
  ('Dalva de Oliveira', 'dalva de oliveira'),
  ('Daniel', 'daniel'),
  ('Daniel Caesar', 'daniel caesar'),
  ('Daniela Mercury', 'daniela mercury'),
  ('Danilo Caymmi', 'danilo caymmi'),
  ('Danny Gatton', 'danny gatton'),
  ('Dark Angel', 'dark angel'),
  ('Dark Tranquillity', 'dark tranquillity'),
  ('Darkthrone', 'darkthrone'),
  ('Dave Brubeck', 'dave brubeck'),
  ('Dave Mason', 'dave mason'),
  ('David Bowie', 'david bowie'),
  ('David Sanborn', 'david sanborn'),
  ('De La Soul', 'de la soul'),
  ('Dead Boys', 'dead boys'),
  ('Dead Fish', 'dead fish'),
  ('Dead Kennedys', 'dead kennedys'),
  ('Dead or Alive', 'dead or alive'),
  ('Dean Martin', 'dean martin'),
  ('Death', 'death'),
  ('Death Angel', 'death angel'),
  ('Death Cab for Cutie', 'death cab for cutie'),
  ('Death From Above 1979', 'death from above 1979'),
  ('Deep Purple', 'deep purple'),
  ('Def Leppard', 'def leppard'),
  ('Defalla', 'defalla'),
  ('Deftones', 'deftones'),
  ('Deicide', 'deicide'),
  ('Del Shannon', 'del shannon'),
  ('Demon', 'demon'),
  ('Demônios da Garoa', 'demonios da garoa'),
  ('Deny e Dino', 'deny e dino'),
  ('Denzel Curry', 'denzel curry'),
  ('Depeche Mode', 'depeche mode'),
  ('Derek and the Dominos', 'derek and the dominos'),
  ('Derek Trucks', 'derek trucks'),
  ('Detonautas', 'detonautas'),
  ('Devotos', 'devotos'),
  ('Devotos de Nossa Senhora Aparecida', 'devotos de nossa senhora aparecida'),
  ('Dexter Gordon', 'dexter gordon'),
  ('Diamond Head', 'diamond head'),
  ('Diana Krall', 'diana krall'),
  ('Diana Ross', 'diana ross'),
  ('Dick Farney', 'dick farney'),
  ('Dicró', 'dicro'),
  ('Digable Planets', 'digable planets'),
  ('Diiv', 'diiv'),
  ('Dilsinho', 'dilsinho'),
  ('Dimmu Borgir', 'dimmu borgir'),
  ('Dinosaur Jr.', 'dinosaur jr'),
  ('Dio', 'dio'),
  ('Dismember', 'dismember'),
  ('Djavan', 'djavan'),
  ('Djonga', 'djonga'),
  ('Doc Watson', 'doc watson'),
  ('Dolly Parton', 'dolly parton'),
  ('Dom Salvador', 'dom salvador'),
  ('Dom Um Romão', 'dom um romao'),
  ('Domi and JD Beck', 'domi and jd beck'),
  ('Dominguinhos', 'dominguinhos'),
  ('Dona Ivone Lara', 'dona ivone lara'),
  ('Donald Byrd', 'donald byrd'),
  ('Donny Hathaway', 'donny hathaway'),
  ('Dori Caymmi', 'dori caymmi'),
  ('Doris Monteiro', 'doris monteiro'),
  ('Dorsal Atlântica', 'dorsal atlantica'),
  ('Dr. Dre', 'dr dre'),
  ('Dr. Sin', 'dr sin'),
  ('Drake', 'drake'),
  ('Dream Theater', 'dream theater'),
  ('Drive-By Truckers', 'drive by truckers'),
  ('Dry Cleaning', 'dry cleaning'),
  ('Dua Lipa', 'dua lipa'),
  ('Duda Beat', 'duda beat'),
  ('Duffy', 'duffy'),
  ('Duquesa', 'duquesa'),
  ('Dust', 'dust'),
  ('Dusty Springfield', 'dusty springfield'),
  ('Eagles', 'eagles'),
  ('Earl Hooker', 'earl hooker'),
  ('Earl Sweatshirt', 'earl sweatshirt'),
  ('Earth, Wind & Fire', 'earth wind fire'),
  ('Eartheater', 'eartheater'),
  ('EarthGang', 'earthgang'),
  ('Ebony', 'ebony'),
  ('Echo & the Bunnymen', 'echo the bunnymen'),
  ('Ed Motta', 'ed motta'),
  ('Eddie Cochran', 'eddie cochran'),
  ('Edguy', 'edguy'),
  ('Edison Machado', 'edison machado'),
  ('Édith Piaf', 'edith piaf'),
  ('Editors', 'editors'),
  ('Ednardo', 'ednardo'),
  ('Edu Lobo', 'edu lobo'),
  ('Eduardo Araújo', 'eduardo araujo'),
  ('Egberto Gismonti', 'egberto gismonti'),
  ('Egg', 'egg'),
  ('Egotrip', 'egotrip'),
  ('Electric Light Orchestra', 'electric light orchestra'),
  ('Electric Six', 'electric six'),
  ('Eleventh House', 'eleventh house'),
  ('Eliana Pittman', 'eliana pittman'),
  ('Eliete legal', 'eliete legal'),
  ('Elis Regina', 'elis regina'),
  ('Ella Fitzgerald', 'ella fitzgerald'),
  ('Elliott Smith', 'elliott smith'),
  ('Elmore James', 'elmore james'),
  ('Elomar', 'elomar'),
  ('Eloy', 'eloy'),
  ('Elton John', 'elton john'),
  ('Elvin Bishop', 'elvin bishop'),
  ('Elvin Jones', 'elvin jones'),
  ('Elvis Presley', 'elvis presley'),
  ('Elza Soares', 'elza soares'),
  ('Emerson, Lake & Palmer', 'emerson lake palmer'),
  ('Emicida', 'emicida'),
  ('Emilinha Borba', 'emilinha borba'),
  ('Eminem', 'eminem'),
  ('Emmylou Harris', 'emmylou harris'),
  ('Emperor', 'emperor'),
  ('Empire of the Sun', 'empire of the sun'),
  ('Engenheiros do Hawaii', 'engenheiros do hawaii'),
  ('English Teacher', 'english teacher'),
  ('Enslaved', 'enslaved'),
  ('Entombed', 'entombed'),
  ('Enya', 'enya'),
  ('Erasmo Carlos', 'erasmo carlos'),
  ('Erasure', 'erasure'),
  ('Eric B. & Rakim', 'eric b rakim'),
  ('Eric Clapton', 'eric clapton'),
  ('Eric Dolphy', 'eric dolphy'),
  ('Eric Johnson', 'eric johnson'),
  ('Eros Ramazzotti', 'eros ramazzotti'),
  ('Estelle', 'estelle'),
  ('Esther Phillips', 'esther phillips'),
  ('Etta James', 'etta james'),
  ('Eumir Deodato', 'eumir deodato'),
  ('Evaldo Braga', 'evaldo braga'),
  ('Evolução', 'evolucao'),
  ('Exaltasamba', 'exaltasamba'),
  ('Exodus', 'exodus'),
  ('Ezra Collective', 'ezra collective'),
  ('Fabrizio De André', 'fabrizio de andre'),
  ('Facção Central', 'faccao central'),
  ('Fafá de Belém', 'fafa de belem'),
  ('Fagner', 'fagner'),
  ('Fairport Convention', 'fairport convention'),
  ('Faithless', 'faithless'),
  ('Fall Out Boy', 'fall out boy'),
  ('Family', 'family'),
  ('Father John Misty', 'father john misty'),
  ('Fatima Guedes', 'fatima guedes'),
  ('Faust', 'faust'),
  ('Fernanda Abreu', 'fernanda abreu'),
  ('Fernando Mendes', 'fernando mendes'),
  ('Ferrugem', 'ferrugem'),
  ('Fields of the Nephilim', 'fields of the nephilim'),
  ('Filipe Ret', 'filipe ret'),
  ('Finis Africae', 'finis africae'),
  ('Fiona Apple', 'fiona apple'),
  ('Fist', 'fist'),
  ('FKA Twigs', 'fka twigs'),
  ('Flávio Venturini', 'flavio venturini'),
  ('Fleet Foxes', 'fleet foxes'),
  ('Fleetwood Mac', 'fleetwood mac'),
  ('Flo', 'flo'),
  ('Floating Points', 'floating points'),
  ('Flora Purim', 'flora purim'),
  ('Florence Welch', 'florence welch'),
  ('Flotsam and Jetsam', 'flotsam and jetsam'),
  ('FM-84', 'fm 84'),
  ('Foals', 'foals'),
  ('Fogo Cruzado', 'fogo cruzado'),
  ('Fontaines D.C.', 'fontaines d c'),
  ('Foo Fighters', 'foo fighters'),
  ('Forbidden', 'forbidden'),
  ('Foreigner', 'foreigner'),
  ('Forfun', 'forfun'),
  ('Foster the People', 'foster the people'),
  ('Fotheringay', 'fotheringay'),
  ('France Gall', 'france gall'),
  ('Francis Hime', 'francis hime'),
  ('Francisco Alves', 'francisco alves'),
  ('Francisco el Hombre', 'francisco el hombre'),
  ('Françoise Hardy', 'francoise hardy'),
  ('Frank Ocean', 'frank ocean'),
  ('Frank Sinatra', 'frank sinatra'),
  ('Frank Zappa', 'frank zappa'),
  ('Franz Ferdinand', 'franz ferdinand'),
  ('Fred again..', 'fred again'),
  ('Freddie Hubbard', 'freddie hubbard'),
  ('Freddie Jackson', 'freddie jackson'),
  ('Freddie King', 'freddie king'),
  ('Freddie Mercury', 'freddie mercury'),
  ('Freddie Roach', 'freddie roach'),
  ('Free', 'free'),
  ('Frejat', 'frejat'),
  ('Fresno', 'fresno'),
  ('Froid', 'froid'),
  ('Front 242', 'front 242'),
  ('Frumpy', 'frumpy'),
  ('Fugazi', 'fugazi'),
  ('Fugees', 'fugees'),
  ('Fundo de Quintal', 'fundo de quintal'),
  ('Funkadelic', 'funkadelic'),
  ('Future', 'future'),
  ('Gabor Szabo', 'gabor szabo'),
  ('Gal Costa', 'gal costa'),
  ('Gamma Ray', 'gamma ray'),
  ('Gang 90 e Absurdettes', 'gang 90 e absurdettes'),
  ('Gang 90 e das Absurdettes', 'gang 90 e das absurdettes'),
  ('Gang of Four', 'gang of four'),
  ('Gang Starr', 'gang starr'),
  ('Garotos Podres', 'garotos podres'),
  ('Gary Moore', 'gary moore'),
  ('Gary Numan', 'gary numan'),
  ('Geese', 'geese'),
  ('Gene Vincent', 'gene vincent'),
  ('Generation X', 'generation x'),
  ('Genesis', 'genesis'),
  ('Gentle Giant', 'gentle giant'),
  ('Geordie', 'geordie'),
  ('George Benson', 'george benson'),
  ('George Harrison', 'george harrison'),
  ('George Jones', 'george jones'),
  ('Georges Brassens', 'georges brassens'),
  ('Gera Samba', 'gera samba'),
  ('Geraldo Azevedo', 'geraldo azevedo'),
  ('Geraldo Filme', 'geraldo filme'),
  ('Geraldo Vandré', 'geraldo vandre'),
  ('Gerson Filho', 'gerson filho'),
  ('Gerson King Combo', 'gerson king combo'),
  ('Gianna Nannini', 'gianna nannini'),
  ('Gilbert Bécaud', 'gilbert becaud'),
  ('Gilberto Gil', 'gilberto gil'),
  ('Gilgamesh', 'gilgamesh'),
  ('Gilliard', 'gilliard'),
  ('Girls Aloud', 'girls aloud'),
  ('Girlschool', 'girlschool'),
  ('Giveon', 'giveon'),
  ('Glass Animals', 'glass animals'),
  ('Glen Campbell', 'glen campbell'),
  ('Gloria Groove', 'gloria groove'),
  ('Gojira', 'gojira'),
  ('Gong', 'gong'),
  ('Gorgoroth', 'gorgoroth'),
  ('Gorillaz', 'gorillaz'),
  ('Gotthard', 'gotthard'),
  ('Grachan Moncur III', 'grachan moncur iii'),
  ('Gracie Abrams', 'gracie abrams'),
  ('Graffiti', 'graffiti'),
  ('Graforreia Xilarmônica', 'graforreia xilarmonica'),
  ('Gram Parsons', 'gram parsons'),
  ('Grand Funk Railroad', 'grand funk railroad'),
  ('Grant Green', 'grant green'),
  ('Grapefruit', 'grapefruit'),
  ('Green Day', 'green day'),
  ('Grim Reaper', 'grim reaper'),
  ('Gritando HC', 'gritando hc'),
  ('Grizzly Bear', 'grizzly bear'),
  ('Grobschnitt', 'grobschnitt'),
  ('Grover Washington Jr.', 'grover washington jr'),
  ('Grupo Fundo de Quintal', 'grupo fundo de quintal'),
  ('Grupo Manifesto', 'grupo manifesto'),
  ('Grupo Raça', 'grupo raca'),
  ('Grupo Revelação', 'grupo revelacao'),
  ('Guided by Voices', 'guided by voices'),
  ('Guilherme Arantes', 'guilherme arantes'),
  ('Guilherme de Brito', 'guilherme de brito'),
  ('Guns N'' Roses', 'guns n roses'),
  ('Gunship', 'gunship'),
  ('Guru Guru', 'guru guru'),
  ('Gusttavo Lima', 'gusttavo lima'),
  ('Guthrie Govan', 'guthrie govan'),
  ('Guy Clark', 'guy clark'),
  ('Gwen Stefani', 'gwen stefani'),
  ('H P Lovecraft', 'h p lovecraft'),
  ('Haikaiss', 'haikaiss'),
  ('Haircut 100', 'haircut 100'),
  ('Hamilton de Holanda', 'hamilton de holanda'),
  ('HammerFall', 'hammerfall'),
  ('Hank Mobley', 'hank mobley'),
  ('Hank Williams', 'hank williams'),
  ('Hanói Hanói', 'hanoi hanoi'),
  ('Harmonia', 'harmonia'),
  ('Harppia', 'harppia'),
  ('Hatfield and the North', 'hatfield and the north'),
  ('Hawkwind', 'hawkwind'),
  ('Hawthorne Heights', 'hawthorne heights'),
  ('Headhunters', 'headhunters'),
  ('Heaven 17', 'heaven 17'),
  ('Helio Delmiro', 'helio delmiro'),
  ('Helloween', 'helloween'),
  ('Henrique & Juliano', 'henrique juliano'),
  ('Heraldo do Monte', 'heraldo do monte'),
  ('Herbie Hancock', 'herbie hancock'),
  ('Hermeto Pascoal', 'hermeto pascoal'),
  ('Herva Doce', 'herva doce'),
  ('Hieroglyphics', 'hieroglyphics'),
  ('High Tide', 'high tide'),
  ('Hojerizah', 'hojerizah'),
  ('Holocausto', 'holocausto'),
  ('Homeshake', 'homeshake'),
  ('Hooverphonic', 'hooverphonic'),
  ('Horace Silver', 'horace silver'),
  ('Howard Jones', 'howard jones'),
  ('Howlin'' Wolf', 'howlin wolf'),
  ('Humberto Teixeira', 'humberto teixeira'),
  ('Husker Du', 'husker du'),
  ('Hyldon', 'hyldon'),
  ('Ice Cube', 'ice cube'),
  ('Ice Spice', 'ice spice'),
  ('IDLES', 'idles'),
  ('Iggy Pop', 'iggy pop'),
  ('Imagine Dragons', 'imagine dragons'),
  ('Immortal', 'immortal'),
  ('In Flames', 'in flames'),
  ('Inimigos do Rei', 'inimigos do rei'),
  ('Inocentes', 'inocentes'),
  ('Interpol', 'interpol'),
  ('Ira!', 'ira'),
  ('Irma Thomas', 'irma thomas'),
  ('Iron Butterfly', 'iron butterfly'),
  ('Iron Maiden', 'iron maiden'),
  ('Iron & Wine', 'iron wine'),
  ('Isaac Hayes', 'isaac hayes'),
  ('Isaiah Rashad', 'isaiah rashad'),
  ('Isotope', 'isotope'),
  ('Israel & Rodolffo', 'israel rodolffo'),
  ('It''s a Beautiful Day', 'it s a beautiful day'),
  ('Itamar Assumpção', 'itamar assumpcao'),
  ('Ivete Sangalo', 'ivete sangalo'),
  ('Ivone Lara', 'ivone lara'),
  ('Iza', 'iza'),
  ('J.B. Hutto', 'j b hutto'),
  ('J. Cole', 'j cole'),
  ('J.T. Meirelles', 'j t meirelles'),
  ('Jackie McLean', 'jackie mclean'),
  ('Jackson do Pandeiro', 'jackson do pandeiro'),
  ('Jacopo Pastorius', 'jacopo pastorius'),
  ('Jacques Brel', 'jacques brel'),
  ('Jade Warrior', 'jade warrior'),
  ('Jadsa', 'jadsa'),
  ('Jaguar', 'jaguar'),
  ('Jair Rodrigues', 'jair rodrigues'),
  ('Jane', 'jane'),
  ('Jane Birkin', 'jane birkin'),
  ('Jane Duboc', 'jane duboc'),
  ('Janet Jackson', 'janet jackson'),
  ('Janis Ian', 'janis ian'),
  ('Jão', 'jao'),
  ('Japan', 'japan'),
  ('Jards Macalé', 'jards macale'),
  ('Jay-Z', 'jay z'),
  ('Jeff Beck', 'jeff beck'),
  ('Jeff Buckley', 'jeff buckley'),
  ('Jefferson Airplane', 'jefferson airplane'),
  ('Jennifer Lopez', 'jennifer lopez'),
  ('Jerry Adriani', 'jerry adriani'),
  ('Jerry Lee Lewis', 'jerry lee lewis'),
  ('Jerusalem', 'jerusalem'),
  ('Jethro Tull', 'jethro tull'),
  ('JID', 'jid'),
  ('Jim Hall', 'jim hall'),
  ('Jimi Hendrix', 'jimi hendrix'),
  ('Jimmy Eat World', 'jimmy eat world'),
  ('Jimmy Reed', 'jimmy reed'),
  ('Jimmy Smith', 'jimmy smith'),
  ('Joan Baez', 'joan baez'),
  ('João do Vale', 'joao do vale'),
  ('João Gilberto', 'joao gilberto'),
  ('João Mineiro', 'joao mineiro'),
  ('Joe Bonamassa', 'joe bonamassa'),
  ('Joe Henderson', 'joe henderson'),
  ('Joe Pass', 'joe pass'),
  ('Joe Satriani', 'joe satriani'),
  ('Joe Tex', 'joe tex'),
  ('Joe Walsh', 'joe walsh'),
  ('Joey Bada$$', 'joey bada'),
  ('John Coltrane', 'john coltrane'),
  ('John Frusciante', 'john frusciante'),
  ('John Lee Hooker', 'john lee hooker'),
  ('John Lennon', 'john lennon'),
  ('John Prine', 'john prine'),
  ('John Scofield', 'john scofield'),
  ('Johnny Cash', 'johnny cash'),
  ('Johnny Thunders & The Heartbreakers', 'johnny thunders the heartbreakers'),
  ('Joni Mitchell', 'joni mitchell'),
  ('Jorge Aragão', 'jorge aragao'),
  ('Jorge Ben Jor', 'jorge ben jor'),
  ('Jorge & Mateus', 'jorge mateus'),
  ('Jorge Mautner', 'jorge mautner'),
  ('Joss Stone', 'joss stone'),
  ('Josyara', 'josyara'),
  ('Jota Quest', 'jota quest'),
  ('Journey', 'journey'),
  ('Jovelina Pérola Negra', 'jovelina perola negra'),
  ('Jovem Dionisio', 'jovem dionisio'),
  ('Joy Division', 'joy division'),
  ('Joyce Moreno', 'joyce moreno'),
  ('Juarez Moreira', 'juarez moreira'),
  ('Judas Priest', 'judas priest'),
  ('Judy Collins', 'judy collins'),
  ('Julien Baker', 'julien baker'),
  ('July', 'july'),
  ('Junior Wells', 'junior wells'),
  ('Jup do Bairro', 'jup do bairro'),
  ('Justice', 'justice'),
  ('Justin Timberlake', 'justin timberlake'),
  ('Kaê Guajajara', 'kae guajajara'),
  ('Kajagoogoo', 'kajagoogoo'),
  ('Kamasi Washington', 'kamasi washington'),
  ('Kanye West', 'kanye west'),
  ('Kasabian', 'kasabian'),
  ('Katatonia', 'katatonia'),
  ('Kate Bush', 'kate bush'),
  ('Katinguelê', 'katinguele'),
  ('Katy Perry', 'katy perry'),
  ('kd lang', 'kd lang'),
  ('Keane', 'keane'),
  ('Keb'' Mo''', 'keb mo'),
  ('Keith Jarrett', 'keith jarrett'),
  ('Kelly Clarkson', 'kelly clarkson'),
  ('Kendrick Lamar', 'kendrick lamar'),
  ('Kenny Burrell', 'kenny burrell'),
  ('Kenny Rogers', 'kenny rogers'),
  ('Khalid', 'khalid'),
  ('Kid Abelha', 'kid abelha'),
  ('Kid Cudi', 'kid cudi'),
  ('Kiko Dinucci', 'kiko dinucci'),
  ('Kiko Zambianchi', 'kiko zambianchi'),
  ('Killswitch Engage', 'killswitch engage'),
  ('Kiloucura', 'kiloucura'),
  ('King Crimson', 'king crimson'),
  ('King Diamond', 'king diamond'),
  ('Kings of Leon', 'kings of leon'),
  ('Kiss', 'kiss'),
  ('Klaus Schulze', 'klaus schulze'),
  ('KMFDM', 'kmfdm'),
  ('Knower', 'knower'),
  ('Koko Taylor', 'koko taylor'),
  ('Kool & The Gang', 'kool the gang'),
  ('Korn', 'korn'),
  ('Korzus', 'korzus'),
  ('Kraftwerk', 'kraftwerk'),
  ('Kris Kristofferson', 'kris kristofferson'),
  ('Krisiun', 'krisiun'),
  ('Krokus', 'krokus'),
  ('KRS-One', 'krs one'),
  ('L7', 'l7'),
  ('L7NNON', 'l7nnon'),
  ('Lady Gaga', 'lady gaga'),
  ('Laércio de Freitas', 'laercio de freitas'),
  ('Lamb', 'lamb'),
  ('Lamb of God', 'lamb of god'),
  ('Lana Del Rey', 'lana del rey'),
  ('Lanny Gordin', 'lanny gordin'),
  ('Larry Young', 'larry young'),
  ('Laura Nyro', 'laura nyro'),
  ('Laura Pausini', 'laura pausini'),
  ('Laurindo Almeida', 'laurindo almeida'),
  ('LaVern Baker', 'lavern baker'),
  ('Leci Brandão', 'leci brandao'),
  ('Led Zeppelin', 'led zeppelin'),
  ('Lee Morgan', 'lee morgan'),
  ('Leftfield', 'leftfield'),
  ('Legião Urbana', 'legiao urbana'),
  ('Lenine', 'lenine'),
  ('Leno e Lilian', 'leno e lilian'),
  ('Leny Andrade', 'leny andrade'),
  ('Leo Ferré', 'leo ferre'),
  ('Leo Jaime', 'leo jaime'),
  ('Leonard Cohen', 'leonard cohen'),
  ('Leonardo', 'leonardo'),
  ('Letrux', 'letrux'),
  ('Lifetime', 'lifetime'),
  ('Lightnin'' Hopkins', 'lightnin hopkins'),
  ('Lil Wayne', 'lil wayne'),
  ('Limp Bizkit', 'limp bizkit'),
  ('Lindisfarne', 'lindisfarne'),
  ('Lindomar Castilho', 'lindomar castilho'),
  ('Liniker', 'liniker'),
  ('Linkin Park', 'linkin park'),
  ('Little Feat', 'little feat'),
  ('Little Richard', 'little richard'),
  ('LL Cool J', 'll cool j'),
  ('Lô Borges', 'lo borges'),
  ('Lobão', 'lobao'),
  ('Lorde', 'lorde'),
  ('Loretta Lynn', 'loretta lynn'),
  ('Los Hermanos', 'los hermanos'),
  ('Lou Reed', 'lou reed'),
  ('Louis Armstrong', 'louis armstrong'),
  ('Luan Santana', 'luan santana'),
  ('Lucero', 'lucero'),
  ('Luciano', 'luciano'),
  ('Lucifer''s Friend', 'lucifer s friend'),
  ('Lucinda Williams', 'lucinda williams'),
  ('Lucinha Lins', 'lucinha lins'),
  ('Lúcio Alves', 'lucio alves'),
  ('Lucio Battisti', 'lucio battisti'),
  ('Lucy Dacus', 'lucy dacus'),
  ('Ludacris', 'ludacris'),
  ('Ludmilla', 'ludmilla'),
  ('Luedji Luna', 'luedji luna'),
  ('Luísa Sonza', 'luisa sonza'),
  ('Luiz Carlos da Vila', 'luiz carlos da vila'),
  ('Luiz Eça', 'luiz eca'),
  ('Luiz Gonzaga', 'luiz gonzaga'),
  ('Luiz Melodia', 'luiz melodia'),
  ('Lulu', 'lulu'),
  ('Lulu Santos', 'lulu santos'),
  ('Lupe Fiasco', 'lupe fiasco'),
  ('Luther Allison', 'luther allison'),
  ('Luther Vandross', 'luther vandross'),
  ('Lyle Lovett', 'lyle lovett'),
  ('Lynyrd Skynyrd', 'lynyrd skynyrd'),
  ('Mac DeMarco', 'mac demarco'),
  ('Mac Miller', 'mac miller'),
  ('Made in Brazil', 'made in brazil'),
  ('Madonna', 'madonna'),
  ('Magazine', 'magazine'),
  ('Magdalena Bay', 'magdalena bay'),
  ('Magic Sam', 'magic sam'),
  ('Maglore', 'maglore'),
  ('Mahavishnu Orchestra', 'mahavishnu orchestra'),
  ('Maiara', 'maiara'),
  ('Maiara & Maraisa', 'maiara maraisa'),
  ('Mallu Magalhães', 'mallu magalhaes'),
  ('Mance Lipscomb', 'mance lipscomb'),
  ('Maneva', 'maneva'),
  ('Mano Brown', 'mano brown'),
  ('Maraisa', 'maraisa'),
  ('Marcelo D2', 'marcelo d2'),
  ('Marcelo Jeneci', 'marcelo jeneci'),
  ('Márcia', 'marcia'),
  ('Marciano', 'marciano'),
  ('Márcio Greyck', 'marcio greyck'),
  ('Márcio Montarroyos', 'marcio montarroyos'),
  ('Marcos Valle', 'marcos valle'),
  ('Marcus Miller', 'marcus miller'),
  ('Margareth Menezes', 'margareth menezes'),
  ('Maria Bethânia', 'maria bethania'),
  ('Maria Gadú', 'maria gadu'),
  ('Mariah Carey', 'mariah carey'),
  ('Mariana Aydar', 'mariana aydar'),
  ('Marianne Faithfull', 'marianne faithfull'),
  ('Marília Mendonça', 'marilia mendonca'),
  ('Marillion', 'marillion'),
  ('Marilyn Manson', 'marilyn manson'),
  ('Marina Lima', 'marina lima'),
  ('Marinês', 'marines'),
  ('Mário Zan', 'mario zan'),
  ('Marisa Monte', 'marisa monte'),
  ('Mark Knopfler', 'mark knopfler'),
  ('Marlene', 'marlene'),
  ('Maroon 5', 'maroon 5'),
  ('Martinho da Vila', 'martinho da vila'),
  ('Marvin Gaye', 'marvin gaye'),
  ('Márvio Ciribelli', 'marvio ciribelli'),
  ('Maskavo', 'maskavo'),
  ('Massive Attack', 'massive attack'),
  ('Mastodon', 'mastodon'),
  ('Matching Mole', 'matching mole'),
  ('Mateus Faz Leno', 'mateus faz leno'),
  ('Matheus & Kauan', 'matheus kauan'),
  ('Matuê', 'matue'),
  ('Mauro Diniz', 'mauro diniz'),
  ('Max Roach', 'max roach'),
  ('Maxïmo Park', 'maximo park'),
  ('May Blitz', 'may blitz'),
  ('Mayhem', 'mayhem'),
  ('Mayitz', 'mayitz'),
  ('MC5', 'mc5'),
  ('Meat Beat Manifesto', 'meat beat manifesto'),
  ('Megadeth', 'megadeth'),
  ('Meirelles e Os Copa 5', 'meirelles e os copa 5'),
  ('Melanie', 'melanie'),
  ('Melly', 'melly'),
  ('Melvins', 'melvins'),
  ('Mercyful Fate', 'mercyful fate'),
  ('Merle Haggard', 'merle haggard'),
  ('Meshuggah', 'meshuggah'),
  ('Messias Holanda', 'messias holanda'),
  ('Metá Metá', 'meta meta'),
  ('Metallica', 'metallica'),
  ('Metalmorphose', 'metalmorphose'),
  ('Metrô', 'metro'),
  ('MGMT', 'mgmt'),
  ('Michael Jackson', 'michael jackson'),
  ('Michel Polnareff', 'michel polnareff'),
  ('Michel Teló', 'michel telo'),
  ('Miguel', 'miguel'),
  ('Mike Bloomfield', 'mike bloomfield'),
  ('Miles Davis', 'miles davis'),
  ('Milionário e José Rico', 'milionario e jose rico'),
  ('Miltinho', 'miltinho'),
  ('Milton Banana', 'milton banana'),
  ('Milton Nascimento', 'milton nascimento'),
  ('Mina', 'mina'),
  ('Ministry', 'ministry'),
  ('Minor Threat', 'minor threat'),
  ('Minutemen', 'minutemen'),
  ('Mississippi Fred McDowell', 'mississippi fred mcdowell'),
  ('Mississippi John Hurt', 'mississippi john hurt'),
  ('Mitski', 'mitski'),
  ('Moacyr Franco', 'moacyr franco'),
  ('Mobb Deep', 'mobb deep'),
  ('Moby Grape', 'moby grape'),
  ('Modest Mouse', 'modest mouse'),
  ('Modulo 1000', 'modulo 1000'),
  ('Molejo', 'molejo'),
  ('Mombojó', 'mombojo'),
  ('Monarco', 'monarco'),
  ('Moonspell', 'moonspell'),
  ('Morbid Angel', 'morbid angel'),
  ('Morengueira', 'morengueira'),
  ('Morrissey', 'morrissey'),
  ('Mos Def', 'mos def'),
  ('Moska', 'moska'),
  ('Moto Perpétuo', 'moto perpetuo'),
  ('Motörhead', 'motorhead'),
  ('Mott the Hoople', 'mott the hoople'),
  ('Mountain', 'mountain'),
  ('Móveis Coloniais de Acaju', 'moveis coloniais de acaju'),
  ('MPB4', 'mpb4'),
  ('Mud', 'mud'),
  ('Muddy Waters', 'muddy waters'),
  ('Mudhoney', 'mudhoney'),
  ('Mumuzinho', 'mumuzinho'),
  ('Mundo Livre S/A', 'mundo livre s a'),
  ('Muse', 'muse'),
  ('Mutilator', 'mutilator'),
  ('MV Bill', 'mv bill'),
  ('My Chemical Romance', 'my chemical romance'),
  ('My Dying Bride', 'my dying bride'),
  ('N.W.A', 'n w a'),
  ('Nação Zumbi', 'nacao zumbi'),
  ('Naipe', 'naipe'),
  ('Nala Sinephro', 'nala sinephro'),
  ('Nana Caymmi', 'nana caymmi'),
  ('Naná Vasconcelos', 'nana vasconcelos'),
  ('Nara Leão', 'nara leao'),
  ('Nas', 'nas'),
  ('Nat King Cole', 'nat king cole'),
  ('Natasha Bedingfield', 'natasha bedingfield'),
  ('National Health', 'national health'),
  ('Natiruts', 'natiruts'),
  ('Ne-Yo', 'ne yo'),
  ('Negritude Junior', 'negritude junior'),
  ('Neil Young', 'neil young'),
  ('Nelly Furtado', 'nelly furtado'),
  ('Nelson Cavaquinho', 'nelson cavaquinho'),
  ('Nelson Gonçalves', 'nelson goncalves'),
  ('Nelson Ned', 'nelson ned'),
  ('Nenhum de Nós', 'nenhum de nos'),
  ('Neu!', 'neu'),
  ('Neutral Milk Hotel', 'neutral milk hotel'),
  ('New Order', 'new order'),
  ('New York Dolls', 'new york dolls'),
  ('Ney Matogrosso', 'ney matogrosso'),
  ('Nick Cave', 'nick cave'),
  ('Nick Drake', 'nick drake'),
  ('Nico', 'nico'),
  ('Nightwish', 'nightwish'),
  ('Nik Kershaw', 'nik kershaw'),
  ('Nina Simone', 'nina simone'),
  ('Nine Inch Nails', 'nine inch nails'),
  ('Nirvana', 'nirvana'),
  ('Nivaldo Ornelas', 'nivaldo ornelas'),
  ('NOFX', 'nofx'),
  ('Noname', 'noname'),
  ('Norah Jones', 'norah jones'),
  ('Notorious B.I.G.', 'notorious b i g'),
  ('Novalis', 'novalis'),
  ('Novos Baianos', 'novos baianos'),
  ('Nuclear Assault', 'nuclear assault'),
  ('Nucleus', 'nucleus'),
  ('Nx Zero', 'nx zero'),
  ('O Rappa', 'o rappa'),
  ('O Terço', 'o terco'),
  ('O Terno', 'o terno'),
  ('Obituary', 'obituary'),
  ('Odair José', 'odair jose'),
  ('Old 97''s', 'old 97 s'),
  ('Olho Seco', 'olho seco'),
  ('Olive', 'olive'),
  ('Oliver Nelson', 'oliver nelson'),
  ('Olivia Dean', 'olivia dean'),
  ('Olivia Rodrigo', 'olivia rodrigo'),
  ('Olodum', 'olodum'),
  ('OneRepublic', 'onerepublic'),
  ('Opeth', 'opeth'),
  ('Orbital', 'orbital'),
  ('Orchestral Manoeuvres in the Dark', 'orchestral manoeuvres in the dark'),
  ('Oriente', 'oriente'),
  ('Orlando Silva', 'orlando silva'),
  ('Ornette Coleman', 'ornette coleman'),
  ('Orquestra Imperial', 'orquestra imperial'),
  ('Os 3 do Nordeste', 'os 3 do nordeste'),
  ('Os Caçulas', 'os caculas'),
  ('Os Cariocas', 'os cariocas'),
  ('Os Cascavelletes', 'os cascavelletes'),
  ('Os Diagonais', 'os diagonais'),
  ('Os Golden Boys', 'os golden boys'),
  ('Os Incríveis', 'os incriveis'),
  ('Os Ipanemas', 'os ipanemas'),
  ('Os Mutantes', 'os mutantes'),
  ('Os Renato e Seus Blue Caps', 'os renato e seus blue caps'),
  ('Os Tincoãs', 'os tincoas'),
  ('Os Travessos', 'os travessos'),
  ('Os Vips', 'os vips'),
  ('Osmar Milito', 'osmar milito'),
  ('Oswaldinho do Acordeon', 'oswaldinho do acordeon'),
  ('Otis Redding', 'otis redding'),
  ('Otis Rush', 'otis rush'),
  ('Outkast', 'outkast'),
  ('Overdose', 'overdose'),
  ('Overkill', 'overkill'),
  ('Ozzy Osbourne', 'ozzy osbourne'),
  ('Pabllo Vittar', 'pabllo vittar'),
  ('Panic! At The Disco', 'panic at the disco'),
  ('Pantera', 'pantera'),
  ('Paolo Conte', 'paolo conte'),
  ('Paradise Lost', 'paradise lost'),
  ('Paralamas do Sucesso', 'paralamas do sucesso'),
  ('Paramore', 'paramore'),
  ('Pardinho', 'pardinho'),
  ('Parkway Drive', 'parkway drive'),
  ('Parliament', 'parliament'),
  ('Passacoita', 'passacoita'),
  ('Passport', 'passport'),
  ('Pat Metheny', 'pat metheny'),
  ('Pato Fu', 'pato fu'),
  ('Patrulha do Espaço', 'patrulha do espaco'),
  ('Paul Butterfield', 'paul butterfield'),
  ('Paul Gilbert', 'paul gilbert'),
  ('Paul McCartney', 'paul mccartney'),
  ('Paul Young', 'paul young'),
  ('Paula Fernandes', 'paula fernandes'),
  ('Paulinho da Viola', 'paulinho da viola'),
  ('Paulo Bellinati', 'paulo bellinati'),
  ('Paulo Moura', 'paulo moura'),
  ('Paulo Sérgio', 'paulo sergio'),
  ('Pavement', 'pavement'),
  ('Pavilhão 9', 'pavilhao 9'),
  ('Peabo Bryson', 'peabo bryson'),
  ('Pearl Jam', 'pearl jam'),
  ('Pena Branca', 'pena branca'),
  ('Pentangle', 'pentangle'),
  ('Percy Sledge', 'percy sledge'),
  ('Péricles', 'pericles'),
  ('Perigeo', 'perigeo'),
  ('Periphery', 'periphery'),
  ('Perturbator', 'perturbator'),
  ('Pery Ribeiro', 'pery ribeiro'),
  ('Peso', 'peso'),
  ('Pet Shop Boys', 'pet shop boys'),
  ('Pete Rock & CL Smooth', 'pete rock cl smooth'),
  ('Peter Gabriel', 'peter gabriel'),
  ('Petula Clark', 'petula clark'),
  ('Pharoah Sanders', 'pharoah sanders'),
  ('Phil Collins', 'phil collins'),
  ('Phoebe Bridgers', 'phoebe bridgers'),
  ('Phoenix', 'phoenix'),
  ('Picassos Falsos', 'picassos falsos'),
  ('Pineapple StormTV', 'pineapple stormtv'),
  ('Pink', 'pink'),
  ('Pink Floyd', 'pink floyd'),
  ('PinkPantheress', 'pinkpantheress'),
  ('Pino Daniele', 'pino daniele'),
  ('Pinto do Acordeão', 'pinto do acordeao'),
  ('Pitty', 'pitty'),
  ('Pixies', 'pixies'),
  ('Pixote', 'pixote'),
  ('PJ Harvey', 'pj harvey'),
  ('Planet Hemp', 'planet hemp'),
  ('Planta e Raiz', 'planta e raiz'),
  ('Plebe Rude', 'plebe rude'),
  ('Ponto de Equilíbrio', 'ponto de equilibrio'),
  ('Popol Vuh', 'popol vuh'),
  ('Porcupine Tree', 'porcupine tree'),
  ('Portishead', 'portishead'),
  ('Possessed', 'possessed'),
  ('Post Malone', 'post malone'),
  ('Praying Mantis', 'praying mantis'),
  ('Prefab Sprout', 'prefab sprout'),
  ('Preta Gil', 'preta gil'),
  ('Pretty Maids', 'pretty maids'),
  ('Prince', 'prince'),
  ('Principal Edwards Magic Theatre', 'principal edwards magic theatre'),
  ('Propaganda', 'propaganda'),
  ('Public Enemy', 'public enemy'),
  ('Public Image Ltd', 'public image ltd'),
  ('Pusha T', 'pusha t'),
  ('Quarteto em Cy', 'quarteto em cy'),
  ('Queen', 'queen'),
  ('Quicksilver Messenger Service', 'quicksilver messenger service'),
  ('Quinteto Violado', 'quinteto violado'),
  ('R.E.M.', 'r e m'),
  ('Raça Negra', 'raca negra'),
  ('Rachel Reis', 'rachel reis'),
  ('Racionais MC''s', 'racionais mc s'),
  ('Radio Birdman', 'radio birdman'),
  ('Rádio Táxi', 'radio taxi'),
  ('Radiohead', 'radiohead'),
  ('Rage Against the Machine', 'rage against the machine'),
  ('Raimundos', 'raimundos'),
  ('Rainbow', 'rainbow'),
  ('Rakim', 'rakim'),
  ('Rammstein', 'rammstein'),
  ('Rancid', 'rancid'),
  ('Raphael Rabello', 'raphael rabello'),
  ('Rashid', 'rashid'),
  ('Ratos de Porão', 'ratos de porao'),
  ('Raul Seixas', 'raul seixas'),
  ('Raven', 'raven'),
  ('Ray Charles', 'ray charles'),
  ('Raye', 'raye'),
  ('Razorlight', 'razorlight'),
  ('Real Estate', 'real estate'),
  ('Recordando o Vale das Maçãs', 'recordando o vale das macas'),
  ('Red Hot Chili Peppers', 'red hot chili peppers'),
  ('Reflection Eternal', 'reflection eternal'),
  ('Reflexu''s', 'reflexu s'),
  ('Reginaldo Rossi', 'reginaldo rossi'),
  ('Reinaldo', 'reinaldo'),
  ('Renaissance', 'renaissance'),
  ('Renato Russo', 'renato russo'),
  ('Renato Teixeira', 'renato teixeira'),
  ('REO Speedwagon', 'reo speedwagon'),
  ('Replicantes', 'replicantes'),
  ('Restos de Nada', 'restos de nada'),
  ('Return to Forever', 'return to forever'),
  ('Reverend Gary Davis', 'reverend gary davis'),
  ('Rhapsody of Fire', 'rhapsody of fire'),
  ('Richard Hell and the Voidoids', 'richard hell and the voidoids'),
  ('Rick Derringer', 'rick derringer'),
  ('Rickie Lee Jones', 'rickie lee jones'),
  ('Ricky Nelson', 'ricky nelson'),
  ('Rihanna', 'rihanna'),
  ('Rincón Sapiência', 'rincon sapiencia'),
  ('Ringo Starr', 'ringo starr'),
  ('Rita Lee', 'rita lee'),
  ('Ritchie', 'ritchie'),
  ('Rob Halford', 'rob halford'),
  ('Rob Zombie', 'rob zombie'),
  ('Robert Johnson', 'robert johnson'),
  ('Robertinho do Acordeon', 'robertinho do acordeon'),
  ('Roberto Carlos', 'roberto carlos'),
  ('Roberto Ribeiro', 'roberto ribeiro'),
  ('Robin Trower', 'robin trower'),
  ('Rock Goddess', 'rock goddess'),
  ('Rod Stewart', 'rod stewart'),
  ('Roland Kirk', 'roland kirk'),
  ('Rômulo Fróes', 'romulo froes'),
  ('Ronnie Montrose', 'ronnie montrose'),
  ('Ronnie Von', 'ronnie von'),
  ('Rory Gallagher', 'rory gallagher'),
  ('Rosinha de Valença', 'rosinha de valenca'),
  ('Rotting Christ', 'rotting christ'),
  ('Roupa Nova', 'roupa nova'),
  ('Roxy Music', 'roxy music'),
  ('Roy Buchanan', 'roy buchanan'),
  ('Roy Haynes', 'roy haynes'),
  ('Roy Orbison', 'roy orbison'),
  ('RPM', 'rpm'),
  ('Run-D.M.C.', 'run d m c'),
  ('Rush', 'rush'),
  ('Ruth Brown', 'ruth brown'),
  ('RZO', 'rzo'),
  ('Sá e Guarabyra', 'sa e guarabyra'),
  ('Sá, Rodrix & Guarabyra', 'sa rodrix guarabyra'),
  ('Saba', 'saba'),
  ('Sabotage', 'sabotage'),
  ('Sabrina Carpenter', 'sabrina carpenter'),
  ('Sacred Reich', 'sacred reich'),
  ('Sad Lovers & Giants', 'sad lovers giants'),
  ('Sade', 'sade'),
  ('Sadus', 'sadus'),
  ('Salário Mínimo', 'salario minimo'),
  ('Sam Cooke', 'sam cooke'),
  ('Sambalanço Trio', 'sambalanco trio'),
  ('Sampa Crew', 'sampa crew'),
  ('Sampha', 'sampha'),
  ('Samson', 'samson'),
  ('Sandi Shaw', 'sandi shaw'),
  ('Sandra de Sá', 'sandra de sa'),
  ('Santana', 'santana'),
  ('Saosin', 'saosin'),
  ('Sarah Vaughan', 'sarah vaughan'),
  ('Sarcófago', 'sarcofago'),
  ('Satyricon', 'satyricon'),
  ('Saxon', 'saxon'),
  ('Scalene', 'scalene'),
  ('Scorpions', 'scorpions'),
  ('Screaming Trees', 'screaming trees'),
  ('Scritti Politti', 'scritti politti'),
  ('Sebastião Tapajós', 'sebastiao tapajos'),
  ('Secos & Molhados', 'secos molhados'),
  ('Sem Compromisso', 'sem compromisso'),
  ('Sempre Livre', 'sempre livre'),
  ('Sensação', 'sensacao'),
  ('Senses Fail', 'senses fail'),
  ('Septicflesh', 'septicflesh'),
  ('Sepultura', 'sepultura'),
  ('Serge Gainsbourg', 'serge gainsbourg'),
  ('Serginho Meriti', 'serginho meriti'),
  ('Sergio Mendes', 'sergio mendes'),
  ('Sérgio Mendes & Brasil ''66', 'sergio mendes brasil 66'),
  ('Sergio Reis', 'sergio reis'),
  ('Sérgio Sampaio', 'sergio sampaio'),
  ('Seu Jorge', 'seu jorge'),
  ('Sex Pistols', 'sex pistols'),
  ('Shabaka Hutchings', 'shabaka hutchings'),
  ('Shadows Fall', 'shadows fall'),
  ('Shakira', 'shakira'),
  ('Shaman', 'shaman'),
  ('Shame', 'shame'),
  ('Sheryl Crow', 'sheryl crow'),
  ('Shygirl', 'shygirl'),
  ('Silva', 'silva'),
  ('Silverstein', 'silverstein'),
  ('Silvinha Araújo', 'silvinha araujo'),
  ('Silvinho', 'silvinho'),
  ('Simaria', 'simaria'),
  ('Simon & Garfunkel', 'simon garfunkel'),
  ('Simone Mendes', 'simone mendes'),
  ('Simple Minds', 'simple minds'),
  ('Simple Plan', 'simple plan'),
  ('Sinéad O''Connor', 'sinead o connor'),
  ('Siouxsie and the Banshees', 'siouxsie and the banshees'),
  ('Sir Lord Baltimore', 'sir lord baltimore'),
  ('Sister Rosetta Tharpe', 'sister rosetta tharpe'),
  ('Sister Sledge', 'sister sledge'),
  ('Sisters of Mercy', 'sisters of mercy'),
  ('Sivuca', 'sivuca'),
  ('Skank', 'skank'),
  ('Skinny Puppy', 'skinny puppy'),
  ('Skip James', 'skip james'),
  ('Slade', 'slade'),
  ('Slash', 'slash'),
  ('Slayer', 'slayer'),
  ('Slayyyter', 'slayyyter'),
  ('Slim Harpo', 'slim harpo'),
  ('Slipknot', 'slipknot'),
  ('Slobberbone', 'slobberbone'),
  ('Slum Village', 'slum village'),
  ('Sly and the Family Stone', 'sly and the family stone'),
  ('Smashing Pumpkins', 'smashing pumpkins'),
  ('Smino', 'smino'),
  ('Snarky Puppy', 'snarky puppy'),
  ('Sneaker Pimps', 'sneaker pimps'),
  ('SNJ', 'snj'),
  ('Snoop Dogg', 'snoop dogg'),
  ('Snow Patrol', 'snow patrol'),
  ('Soft Cell', 'soft cell'),
  ('Soft Machine', 'soft machine'),
  ('Soilwork', 'soilwork'),
  ('Solomon Burke', 'solomon burke'),
  ('Som Imagina''rio', 'som imagina rio'),
  ('Som Imaginário', 'som imaginario'),
  ('Som Nosso de Cada Dia', 'som nosso de cada dia'),
  ('Sombrinha', 'sombrinha'),
  ('Son Seals', 'son seals'),
  ('Son Volt', 'son volt'),
  ('Sonata Arctica', 'sonata arctica'),
  ('Sonic Youth', 'sonic youth'),
  ('Sonny Boy Williamson II', 'sonny boy williamson ii'),
  ('Sonny Rollins', 'sonny rollins'),
  ('Sons of Kemet', 'sons of kemet'),
  ('Sophia Chablau e Uma Enorme Perda de Tempo', 'sophia chablau e uma enorme perda de tempo'),
  ('Sophie Ellis-Bextor', 'sophie ellis bextor'),
  ('Souls of Mischief', 'souls of mischief'),
  ('Soundgarden', 'soundgarden'),
  ('Soweto', 'soweto'),
  ('Spandau Ballet', 'spandau ballet'),
  ('Spanky and Our Gang', 'spanky and our gang'),
  ('SPC (Só Pra Contrariar)', 'spc so pra contrariar'),
  ('Spirit', 'spirit'),
  ('SpokFrevo Orquestra', 'spokfrevo orquestra'),
  ('Spooky Tooth', 'spooky tooth'),
  ('Spoon', 'spoon'),
  ('Sprints', 'sprints'),
  ('Squid', 'squid'),
  ('St. Vincent', 'st vincent'),
  ('Stan Getz', 'stan getz'),
  ('Starz', 'starz'),
  ('Steeleye Span', 'steeleye span'),
  ('Steely Dan', 'steely dan'),
  ('Steppenwolf', 'steppenwolf'),
  ('Steve Earle', 'steve earle'),
  ('Steve Vai', 'steve vai'),
  ('Steve Winwood', 'steve winwood'),
  ('Stevie Ray Vaughan', 'stevie ray vaughan'),
  ('Stevie Wonder', 'stevie wonder'),
  ('Stiff Little Fingers', 'stiff little fingers'),
  ('Sting', 'sting'),
  ('Stone Temple Pilots', 'stone temple pilots'),
  ('Story of the Year', 'story of the year'),
  ('Stratovarius', 'stratovarius'),
  ('Strawberry Alarm Clock', 'strawberry alarm clock'),
  ('Strawbs', 'strawbs'),
  ('Stray', 'stray'),
  ('Stress', 'stress'),
  ('Strike', 'strike'),
  ('Styx', 'styx'),
  ('Sued Nunes', 'sued nunes'),
  ('Sueli Costa', 'sueli costa'),
  ('Sufjan Stevens', 'sufjan stevens'),
  ('Sugababes', 'sugababes'),
  ('Sum 41', 'sum 41'),
  ('Sun Ra', 'sun ra'),
  ('Superchunk', 'superchunk'),
  ('Supercombo', 'supercombo'),
  ('Supertramp', 'supertramp'),
  ('Suricato', 'suricato'),
  ('Sweet', 'sweet'),
  ('Sylvinha Telles', 'sylvinha telles'),
  ('System of a Down', 'system of a down'),
  ('T. Rex', 't rex'),
  ('Taiguara', 'taiguara'),
  ('Taj Mahal', 'taj mahal'),
  ('Taking Back Sunday', 'taking back sunday'),
  ('Talib Kweli', 'talib kweli'),
  ('Talk Talk', 'talk talk'),
  ('Talking Heads', 'talking heads'),
  ('Tamba Trio', 'tamba trio'),
  ('Tame Impala', 'tame impala'),
  ('Tammy Wynette', 'tammy wynette'),
  ('Tangerine Dream', 'tangerine dream'),
  ('Tânia Maria', 'tania maria'),
  ('Tasha & Tracie', 'tasha tracie'),
  ('Tate McRae', 'tate mcrae'),
  ('Taylor Swift', 'taylor swift'),
  ('Tears for Fears', 'tears for fears'),
  ('Ted Nugent', 'ted nugent'),
  ('Teddy Pendergrass', 'teddy pendergrass'),
  ('Television', 'television'),
  ('Ten Years After', 'ten years after'),
  ('Tenório Jr.', 'tenorio jr'),
  ('Terno Rei', 'terno rei'),
  ('Terreno Baldio', 'terreno baldio'),
  ('Testament', 'testament'),
  ('Tetê da Represa', 'tete da represa'),
  ('Tetê Espíndola', 'tete espindola'),
  ('The 1975', 'the 1975'),
  ('The Action', 'the action'),
  ('The Adverts', 'the adverts'),
  ('The Allman Brothers Band', 'the allman brothers band'),
  ('The Animals', 'the animals'),
  ('The Archies', 'the archies'),
  ('The Association', 'the association'),
  ('The Attack', 'the attack'),
  ('The Automatic', 'the automatic'),
  ('The Avengers', 'the avengers'),
  ('The Beach Boys', 'the beach boys'),
  ('The Beatles', 'the beatles'),
  ('The Birthday Party', 'the birthday party'),
  ('The Black Keys', 'the black keys'),
  ('The Blue Nile', 'the blue nile'),
  ('The BoDeans', 'the bodeans'),
  ('The Bottle Rockets', 'the bottle rockets'),
  ('The Bravery', 'the bravery'),
  ('The Buckinghams', 'the buckinghams'),
  ('The Byrds', 'the byrds'),
  ('The Call', 'the call'),
  ('The Chameleons', 'the chameleons'),
  ('The Champs', 'the champs'),
  ('The Chantays', 'the chantays'),
  ('The Chemical Brothers', 'the chemical brothers'),
  ('The Chocolate Watchband', 'the chocolate watchband'),
  ('The Church', 'the church'),
  ('The Clash', 'the clash'),
  ('The Cleavers', 'the cleavers'),
  ('The Comet Is Coming', 'the comet is coming'),
  ('The Commodores', 'the commodores'),
  ('The Cowsills', 'the cowsills'),
  ('The Cramps', 'the cramps'),
  ('The Creation', 'the creation'),
  ('The Cribs', 'the cribs'),
  ('The Cure', 'the cure'),
  ('The Damned', 'the damned'),
  ('The Dave Clark Five', 'the dave clark five'),
  ('The Dictators', 'the dictators'),
  ('The Doobie Brothers', 'the doobie brothers'),
  ('The Doors', 'the doors'),
  ('The Electric Prunes', 'the electric prunes'),
  ('The Enemy', 'the enemy'),
  ('The Faces', 'the faces'),
  ('The Fall', 'the fall'),
  ('The Fevers', 'the fevers'),
  ('The Fifth Dimension', 'the fifth dimension'),
  ('The Fixx', 'the fixx'),
  ('The Four Tops', 'the four tops'),
  ('The Fratellis', 'the fratellis'),
  ('The Futureheads', 'the futureheads'),
  ('The Germs', 'the germs'),
  ('The Go-Betweens', 'the go betweens'),
  ('The Grass Roots', 'the grass roots'),
  ('The Gun Club', 'the gun club'),
  ('The Hollies', 'the hollies'),
  ('The Hooters', 'the hooters'),
  ('The Housemartins', 'the housemartins'),
  ('The Human League', 'the human league'),
  ('The Idle Race', 'the idle race'),
  ('The Incredible String Band', 'the incredible string band'),
  ('The Isley Brothers', 'the isley brothers'),
  ('The Jackson 5', 'the jackson 5'),
  ('The Jayhawks', 'the jayhawks'),
  ('The Jet Black''s', 'the jet black s'),
  ('The Jimi Hendrix Experience', 'the jimi hendrix experience'),
  ('The Killers', 'the killers'),
  ('The Kinks', 'the kinks'),
  ('The Kooks', 'the kooks'),
  ('The Last Dinner Party', 'the last dinner party'),
  ('The Lemonheads', 'the lemonheads'),
  ('The Libertines', 'the libertines'),
  ('The Lovin'' Spoonful', 'the lovin spoonful'),
  ('The Mamas & the Papas', 'the mamas the papas'),
  ('The Mavericks', 'the mavericks'),
  ('The Members', 'the members'),
  ('The Midnight', 'the midnight'),
  ('The Mission', 'the mission'),
  ('The Modern Lovers', 'the modern lovers'),
  ('The Monkees', 'the monkees'),
  ('The Murder Capital', 'the murder capital'),
  ('The Music Machine', 'the music machine'),
  ('The National', 'the national'),
  ('The Nice', 'the nice'),
  ('The O''Jays', 'the o jays'),
  ('The Offspring', 'the offspring'),
  ('The Orb', 'the orb'),
  ('The Outfield', 'the outfield'),
  ('The Partridge Family', 'the partridge family'),
  ('The Pentangle', 'the pentangle'),
  ('The Pharcyde', 'the pharcyde'),
  ('The Pigeon Detectives', 'the pigeon detectives'),
  ('The Police', 'the police'),
  ('The Postal Service', 'the postal service'),
  ('The Pretty Things', 'the pretty things'),
  ('The Prodigy', 'the prodigy'),
  ('The Psychedelic Furs', 'the psychedelic furs'),
  ('The Ramones', 'the ramones'),
  ('The Replacements', 'the replacements'),
  ('The Rolling Stones', 'the rolling stones'),
  ('The Roots', 'the roots'),
  ('The Ruts', 'the ruts'),
  ('The Saints', 'the saints'),
  ('The Searchers', 'the searchers'),
  ('The Seeds', 'the seeds'),
  ('The Shadows', 'the shadows'),
  ('The Shins', 'the shins'),
  ('The Small Faces', 'the small faces'),
  ('The Smiths', 'the smiths'),
  ('The Soft Machine', 'the soft machine'),
  ('The Sonics', 'the sonics'),
  ('The Sound', 'the sound'),
  ('The Spencer Davis Group', 'the spencer davis group'),
  ('The Spinners', 'the spinners'),
  ('The Spotnicks', 'the spotnicks'),
  ('The Standells', 'the standells'),
  ('The Stooges', 'the stooges'),
  ('The Strokes', 'the strokes'),
  ('The Subways', 'the subways'),
  ('The Supremes', 'the supremes'),
  ('The Surfaris', 'the surfaris'),
  ('The Temptations', 'the temptations'),
  ('The Tornados', 'the tornados'),
  ('The Trammps', 'the trammps'),
  ('The Tremeloes', 'the tremeloes'),
  ('The Triffids', 'the triffids'),
  ('The Troggs', 'the troggs'),
  ('The Turtles', 'the turtles'),
  ('The Used', 'the used'),
  ('The Velvet Underground', 'the velvet underground'),
  ('The Ventures', 'the ventures'),
  ('The Vibrators', 'the vibrators'),
  ('The Wedding Present', 'the wedding present'),
  ('The Weeknd', 'the weeknd'),
  ('The Weirdos', 'the weirdos'),
  ('The White Stripes', 'the white stripes'),
  ('The Who', 'the who'),
  ('The Yardbirds', 'the yardbirds'),
  ('The Young Rascals', 'the young rascals'),
  ('The Zombies', 'the zombies'),
  ('Thelonious Monk', 'thelonious monk'),
  ('Thiaguinho', 'thiaguinho'),
  ('Thin Lizzy', 'thin lizzy'),
  ('Third Ear Band', 'third ear band'),
  ('Thomas Dolby', 'thomas dolby'),
  ('Thompson Twins', 'thompson twins'),
  ('Throwing Muses', 'throwing muses'),
  ('Thursday', 'thursday'),
  ('Tiago Iorc', 'tiago iorc'),
  ('Tiamat', 'tiamat'),
  ('Tião Carreiro', 'tiao carreiro'),
  ('Ties de Souza', 'ties de souza'),
  ('Tihuana', 'tihuana'),
  ('Tim Bernardes', 'tim bernardes'),
  ('Tim Buckley', 'tim buckley'),
  ('Tim Maia', 'tim maia'),
  ('Timbalada', 'timbalada'),
  ('Tina Turner', 'tina turner'),
  ('Tinoco', 'tinoco'),
  ('Titãs', 'titas'),
  ('TNT', 'tnt'),
  ('Toad', 'toad'),
  ('Tokyo Blade', 'tokyo blade'),
  ('Tom Jobim', 'tom jobim'),
  ('Tom Morello', 'tom morello'),
  ('Tom Petty', 'tom petty'),
  ('Tom Waits', 'tom waits'),
  ('Tomorrow', 'tomorrow'),
  ('Tonico', 'tonico'),
  ('Toninho Horta', 'toninho horta'),
  ('Tony Bennett', 'tony bennett'),
  ('Tool', 'tool'),
  ('Toquinho', 'toquinho'),
  ('Tori Amos', 'tori amos'),
  ('Torture Squad', 'torture squad'),
  ('Toto', 'toto'),
  ('Tower of Power', 'tower of power'),
  ('Townes Van Zandt', 'townes van zandt'),
  ('Tracy Chapman', 'tracy chapman'),
  ('Trapeze', 'trapeze'),
  ('Travis Scott', 'travis scott'),
  ('Trees', 'trees'),
  ('Tribo da Periferia', 'tribo da periferia'),
  ('Tribo de Jah', 'tribo de jah'),
  ('Tricky', 'tricky'),
  ('Trio Mocotó', 'trio mocoto'),
  ('Trio Nordestino', 'trio nordestino'),
  ('Trio Parada Dura', 'trio parada dura'),
  ('Trio Virgulino', 'trio virgulino'),
  ('Trivium', 'trivium'),
  ('Tulipa Ruiz', 'tulipa ruiz'),
  ('Tupac Shakur', 'tupac shakur'),
  ('Turíbio Santos', 'turibio santos'),
  ('Turma do Pagode', 'turma do pagode'),
  ('Tutti Frutti', 'tutti frutti'),
  ('Tuyo', 'tuyo'),
  ('TV on the Radio', 'tv on the radio'),
  ('Twenty One Pilots', 'twenty one pilots'),
  ('Two Door Cinema Club', 'two door cinema club'),
  ('Tygers of Pan Tang', 'tygers of pan tang'),
  ('Tyler, the Creator', 'tyler the creator'),
  ('U2', 'u2'),
  ('UFO', 'ufo'),
  ('Ultraje a Rigor', 'ultraje a rigor'),
  ('Ultramen', 'ultramen'),
  ('Ultravox', 'ultravox'),
  ('Uncle Tupelo', 'uncle tupelo'),
  ('Underoath', 'underoath'),
  ('Underworld', 'underworld'),
  ('Unearth', 'unearth'),
  ('União Black', 'uniao black'),
  ('Uriah Heep', 'uriah heep'),
  ('Urias', 'urias'),
  ('Usher', 'usher'),
  ('Vampire Weekend', 'vampire weekend'),
  ('Van der Graaf Generator', 'van der graaf generator'),
  ('Van Halen', 'van halen'),
  ('Vanessa da Mata', 'vanessa da mata'),
  ('Vanguart', 'vanguart'),
  ('Vanilla Fudge', 'vanilla fudge'),
  ('Vardis', 'vardis'),
  ('Veruca Salt', 'veruca salt'),
  ('Vicente Celestino', 'vicente celestino'),
  ('Victor & Leo', 'victor leo'),
  ('Victor Wooten', 'victor wooten'),
  ('Vimana', 'vimana'),
  ('Vince Staples', 'vince staples'),
  ('Vinicius de Moraes', 'vinicius de moraes'),
  ('Vio-Lence', 'vio lence'),
  ('Violent Femmes', 'violent femmes'),
  ('Viper', 'viper'),
  ('Virna Lisi', 'virna lisi'),
  ('Visage', 'visage'),
  ('Vital Farias', 'vital farias'),
  ('Wagner Tiso', 'wagner tiso'),
  ('Waldick Soriano', 'waldick soriano'),
  ('Wallenstein', 'wallenstein'),
  ('Walter Franco', 'walter franco'),
  ('Wanda Sá', 'wanda sa'),
  ('Wanderléa', 'wanderlea'),
  ('Wanderley Cardoso', 'wanderley cardoso'),
  ('Warren Haynes', 'warren haynes'),
  ('Waylon Jennings', 'waylon jennings'),
  ('Wayne Shorter', 'wayne shorter'),
  ('We Are Scientists', 'we are scientists'),
  ('Weather Report', 'weather report'),
  ('Wes Montgomery', 'wes montgomery'),
  ('Wet Leg', 'wet leg'),
  ('Whiskeytown', 'whiskeytown'),
  ('Whitesnake', 'whitesnake'),
  ('Whitney Houston', 'whitney houston'),
  ('Wilco', 'wilco'),
  ('Wild Nothing', 'wild nothing'),
  ('Willie Nelson', 'willie nelson'),
  ('Wilson Moreira', 'wilson moreira'),
  ('Wilson Pickett', 'wilson pickett'),
  ('Wilson Simonal', 'wilson simonal'),
  ('Wire', 'wire'),
  ('Wishbone Ash', 'wishbone ash'),
  ('Witchfynde', 'witchfynde'),
  ('Wizzard', 'wizzard'),
  ('Wu-Tang Clan', 'wu tang clan'),
  ('Xamã', 'xama'),
  ('Xande de Pilares', 'xande de pilares'),
  ('Xangai', 'xangai'),
  ('Xavantinho', 'xavantinho'),
  ('Xenia França', 'xenia franca'),
  ('Xororó', 'xororo'),
  ('Yamandu Costa', 'yamandu costa'),
  ('Yard Act', 'yard act'),
  ('Yello', 'yello'),
  ('Yes', 'yes'),
  ('Yngwie Malmsteen', 'yngwie malmsteen'),
  ('Young Thug', 'young thug'),
  ('Yusef Lateef', 'yusef lateef'),
  ('Yussef Kamaal', 'yussef kamaal'),
  ('Yves Montand', 'yves montand'),
  ('Zé Neto & Cristiano', 'ze neto cristiano'),
  ('Zé Ramalho', 'ze ramalho'),
  ('Zeca Baleiro', 'zeca baleiro'),
  ('Zeca Pagodinho', 'zeca pagodinho'),
  ('Zélia Duncan', 'zelia duncan'),
  ('Zero', 'zero'),
  ('Zezé Di Camargo', 'zeze di camargo'),
  ('Zimbo Trio', 'zimbo trio'),
  ('Zucchero', 'zucchero'),
  ('ZZ Top', 'zz top')
ON CONFLICT (name_norm) DO NOTHING;
